ALTER TABLE "Events"
ADD COLUMN IF NOT EXISTS "assistantHostIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "Organizations"
ADD COLUMN IF NOT EXISTS "hostIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
