import type { AgentPageContext } from './types';

type EventFormInputContext = {
  path: string;
  label: string;
  inputType: string;
  visibleWhen: string;
  requiredWhen: string;
  defaultOrPreset: string;
  createsOrUpdates: string[];
  description: string;
};

type EventFormSectionContext = {
  id: string;
  title: string;
  visibleWhen: string;
  summary: string;
  inputs: EventFormInputContext[];
};

type EventFormCapabilityContext = {
  id: string;
  title: string;
  appliesWhen: string;
  composedFrom: string[];
  description: string;
  setupSteps: string[];
  cautions: string[];
};

export type EventFormAgentContext = {
  id: string;
  sourceComponent: string;
  activeTab: 'details';
  purpose: string;
  answerGuidance: string[];
  capabilities: EventFormCapabilityContext[];
  defaultsAndPresets: string[];
  validationRules: string[];
  sections: EventFormSectionContext[];
};

const visibleAlways = 'Always visible on the event Details tab unless an immutable template, rental, or organization default locks the field.';

export const eventFormAgentContext: EventFormAgentContext = {
  id: 'event-form-details-tab-v1',
  sourceComponent: 'src/app/events/[id]/schedule/components/EventForm.tsx',
  activeTab: 'details',
  purpose: 'Use this context to answer questions from a user who is looking at the EventForm on the event Details tab. It explains what each form input means, what is preset, what is required, and how values are serialized into the event draft used to create or update the event.',
  answerGuidance: [
    'Do not dump this JSON to the user unless they explicitly ask for the raw preprompt or raw field map.',
    'Answer naturally from this context when the user asks what a field does, why it is required, what default to use, or how changing it affects event creation.',
    'If a control is conditional, explain the condition before describing the input.',
    'Do not invent current field values. Use current page context or read tools for live event data when needed.',
    'Use user-facing labels in answers, not internal paths, unless the user asks for implementation details.',
    'For capability questions, inspect the field inventory across sections before saying a workflow is unsupported. Some workflows are composed from Event Type, Divisions, League settings, playoff configuration, and timeslots rather than exposed as a single preset.',
    'If the user describes a workflow using terms that are not literal form labels, identify the nearest supported configuration from the available fields and explain the required toggles/sections. Do not claim a capability is missing just because one queried section did not contain a matching label.',
  ],
  capabilities: [
    {
      id: 'league-regular-season-with-playoff-bracket',
      title: 'League regular season with playoff bracket',
      appliesWhen: 'Use when the user wants preliminary round-robin or standings-based play followed by an elimination bracket inside one event.',
      composedFrom: [
        'Event Type = League',
        'Include playoffs',
        'Single Division or multiple Divisions',
        'Division Playoff Team Count / Playoff Team Count',
        'Split League & Playoff Divisions when regular-season groups and playoff brackets need separate containers',
        'Placement #N mapping from each league division into playoff divisions',
        'Playoffs Configuration / playoff division tournament settings',
        'Weekly Timeslots and Timeslot Divisions',
      ],
      description: 'A League can be configured as a same-event multi-stage workflow: the league schedule provides the regular-season/round-robin phase and standings, and enabled playoffs provide tournament-style bracket configuration for qualifiers. The playoff bracket is not a separate Tournament event by default; it is part of the League configuration.',
      setupSteps: [
        'Set Event Type to League.',
        'Enable Include playoffs.',
        'If one standings table feeds one bracket, keep split league/playoff divisions off and configure Playoffs Configuration.',
        'If separate regular-season divisions should feed separate or tiered brackets, turn off Single Division, enable Split League & Playoff Divisions, create playoff divisions, and map each qualifying placement into a playoff division.',
        'Set playoff team counts at the event or division level as required.',
        'Use timeslots and timeslot divisions to constrain when regular-season and playoff matches can be scheduled.',
      ],
      cautions: [
        'Do not recommend creating a separate Tournament event unless the user explicitly wants separate registrations/events or the desired workflow cannot be represented by league playoff settings.',
        'Split League & Playoff Divisions requires playoffs to be enabled and is disabled when Single Division is on, except for external rental field cases.',
      ],
    },
    {
      id: 'standalone-elimination-tournament',
      title: 'Standalone elimination tournament',
      appliesWhen: 'Use when the user wants a direct single- or double-elimination bracket without a regular-season standings phase in the same form.',
      composedFrom: [
        'Event Type = Tournament',
        'Tournament Format',
        'Winner/loser set counts and points-to-victory',
        'Match or set duration',
        'Rest Time Between Matches',
        'Weekly Timeslots',
      ],
      description: 'Tournament events are bracket-first. The form exposes single- and double-elimination settings, duration controls, rest time, and schedulable timeslots, but does not add a separate standings phase in the tournament type itself.',
      setupSteps: [
        'Set Event Type to Tournament.',
        'Choose Tournament Format.',
        'Configure match/set rules and rest time.',
        'Add timeslots and fields for bracket scheduling.',
      ],
      cautions: [
        'If the user needs a standings-based phase before the bracket, inspect the League regular season with playoff bracket capability before suggesting separate events.',
      ],
    },
    {
      id: 'division-based-registration-and-scheduling',
      title: 'Division-based registration and scheduling',
      appliesWhen: 'Use when teams or participants should be grouped by skill, age, gender, or custom division labels and scheduled separately or selectively.',
      composedFrom: [
        'Single Division',
        'Add Division / Update Division',
        'Register by Division Type',
        'Division Max Teams / Division Max Participants',
        'Division Price and division payment plans',
        'Timeslot Divisions',
      ],
      description: 'Divisions define concrete participant groups and can be used with registration and timeslots. Register by Division Type lets users choose a type while the event assigns them to a matching concrete division.',
      setupSteps: [
        'Turn off Single Division when separate concrete groups are needed.',
        'Add division rows with matching skill/age/gender or custom names.',
        'Enable Register by Division Type if registrants should choose a type rather than a specific concrete division.',
        'Use Timeslot Divisions to restrict which groups can be scheduled in each slot.',
      ],
      cautions: [
        'League and tournament events are team events and may start from single-division defaults; multi-division workflows require intentionally configuring divisions.',
      ],
    },
  ],
  defaultsAndPresets: [
    'When editing, saved event values seed the form. When creating, the page supplies an incoming event draft and the form fills missing values from defaults.',
    'immutableDefaults can prefill and lock values for rental or template-based flows. Locked fields still appear in context but should be described as not editable when immutable.',
    'New events save as UNPUBLISHED in the draft payload. Existing events keep their saved state.',
    'The current signed-in user is used as hostId for new events unless an organization-hosted flow supplies a host.',
    'If a defaultLocation is supplied and the event has no location, address, or coordinates, those defaults seed the location selector.',
    'Event image is required. Existing events use their saved imageId; create flows require selecting one before save.',
    'Sport selection hydrates sportConfig. Changing sport clears matchRulesOverride so event-specific scoring and incident overrides do not carry across incompatible sports.',
    'Leagues and tournaments are always team events. Selecting League or Tournament forces teamSignup true, singleDivision true, and open-ended scheduling on by default for new non-rental flows.',
    'Weekly parent events use timeslots as recurring sessions. New registrations select a slot and occurrence date instead of creating child session events; parentEvent only remains for older parent-linked weekly rows.',
    'If Stripe billing is unavailable for the user or organization, paid-event inputs are disabled and serialized price/payment-plan values resolve to free/default values.',
    'Organization-hosted events use organization fields and organization staff where available. Personal events can create local event fields and invite/search staff directly.',
    'Local event fields default to one generated field named Field 1 when no organization fields or existing event fields are available.',
    'League defaults are gamesPerOpponent 1, includePlayoffs false, matchDurationMinutes 60 for non-set sports, restTimeMinutes 0, and no playoffTeamCount until explicitly chosen.',
    'Tournament defaults are single elimination, winnerSetCount 1, loserSetCount 1, points to victory 21, prize empty, fieldCount 1, restTimeMinutes 0, and matchDurationMinutes 60 unless sport set rules require set duration.',
    'Division defaults come from the selected sport division types, with gender CoEd/Open-like fallback, default skill Open, default age 18+, event-level price, and event-level capacity.',
  ],
  validationRules: [
    'Event name, sport, image, location coordinates, maxParticipants, teamSizeLimit, and at least one division are required before save.',
    'For non-league event types, divisions must not be empty. For leagues, division details and division IDs must stay in sync.',
    'Minimum age must be less than or equal to maximum age when both are supplied.',
    'If scheduling uses a fixed event end, end must be after start. Open-ended scheduling skips that event-level end requirement.',
    'Organization events that require direct field selection must have at least one selected organization field.',
    'If an event-level payment plan is enabled, installment count must match the number of installment amounts and there must be at least one amount. The event price follows the total installment amount.',
    'For weekly parent events, payment-plan due dates are relative day offsets from the session day. Other event types use absolute installment due datetimes.',
    'Division payment plans follow the same count and due-date validation when singleDivision is off. The division price follows the total installment amount.',
    'If league playoffs are enabled, playoffTeamCount is required for single-division leagues. For multi-division leagues, each division needs its own playoffTeamCount.',
    'If split league/playoff divisions are enabled, at least one playoff division is required, each league placement must map to a playoff division, and mapped placements cannot exceed playoff division capacity.',
    'Schedulable events require at least one timeslot. Each timeslot requires at least one field. Repeating slots require at least one weekday, start time, and end time. Non-repeating slots require start and end datetimes.',
    'Timeslot end must be after start. Timeslots on the same field cannot overlap with another same-kind timeslot in the form. External timeslot field conflicts are shown as warnings so the scheduler can avoid overlaps when building matches.',
    'When singleDivision is enabled, every timeslot is serialized with all selected event divisions.',
    'STAFFING official scheduling mode requires enough active officials and eligible positions to fully staff every match.',
  ],
  sections: [
    {
      id: 'basic-information',
      title: 'Basic Information',
      visibleWhen: visibleAlways,
      summary: 'Core public identity for the event. These values become the event name, sport, description, and display image seen by participants.',
      inputs: [
        {
          path: 'imageId',
          label: 'Event Image',
          inputType: 'image uploader',
          visibleWhen: visibleAlways,
          requiredWhen: 'Always required.',
          defaultOrPreset: 'Existing imageId is shown when editing. Create flows start blank unless immutableDefaults supplies an image.',
          createsOrUpdates: ['imageId'],
          description: 'Stores the uploaded File id used for event cards, detail pages, embeds, and schedule views. The form validates that an image is selected before saving.',
        },
        {
          path: 'name',
          label: 'Event Name',
          inputType: 'text input',
          visibleWhen: visibleAlways,
          requiredWhen: 'Always required; max 120 characters.',
          defaultOrPreset: 'Existing or incoming draft name.',
          createsOrUpdates: ['name'],
          description: 'The primary public title of the event. It is trimmed before save and is used anywhere the event is listed, including schedules, registrations, and assistant event references.',
        },
        {
          path: 'sportId',
          label: 'Sport',
          inputType: 'select',
          visibleWhen: visibleAlways,
          requiredWhen: 'Always required.',
          defaultOrPreset: 'Existing sportId is used first. If a matching sport is loaded, sportConfig is hydrated from the sport catalog.',
          createsOrUpdates: ['sportId', 'sportConfig', 'matchRulesOverride'],
          description: 'Chooses the sport template for divisions, set-based scoring defaults, official position templates, and match rule defaults. Changing the sport clears event-specific match-rule overrides so stale rules do not cross sports.',
        },
        {
          path: 'description',
          label: 'Description',
          inputType: 'textarea',
          visibleWhen: visibleAlways,
          requiredWhen: 'Optional; max 1000 characters.',
          defaultOrPreset: 'Existing or incoming draft description, otherwise empty.',
          createsOrUpdates: ['description'],
          description: 'Public explanatory text for participants. It does not affect scheduling logic, permissions, payments, or registration capacity.',
        },
      ],
    },
    {
      id: 'event-details',
      title: 'Event Details',
      visibleWhen: visibleAlways,
      summary: 'High-level event type, capacity, dates, location, pricing, documents, age limits, refund cutoff, registration cutoff, payment plans, and fields.',
      inputs: [
        {
          path: 'eventType',
          label: 'Event Type',
          inputType: 'select',
          visibleWhen: visibleAlways,
          requiredWhen: 'Always required.',
          defaultOrPreset: 'Existing eventType. Create/rental flows can restrict options; rental create flows remove Weekly Event.',
          createsOrUpdates: ['eventType', 'teamSignup', 'singleDivision', 'noFixedEndDateTime'],
          description: 'Controls which form sections and scheduling behavior are active. Event is a simple one-off event. Tournament enables tournament settings and bracket scheduling. League enables league schedule generation, league scoring config, playoffs, and weekly timeslots. Weekly Event creates a recurring parent event whose timeslots become weekly sessions. Selecting League or Tournament forces team registration and single-division defaults because those event types are team competitions.',
        },
        {
          path: 'leagueData.includePlayoffs',
          label: 'Include playoffs',
          inputType: 'checkbox',
          visibleWhen: 'Only visible for League events.',
          requiredWhen: 'Optional, but enabling it makes playoffTeamCount or per-division playoff counts required.',
          defaultOrPreset: 'False for new leagues unless existing event or immutable defaults enable playoffs.',
          createsOrUpdates: ['includePlayoffs', 'leagueData.includePlayoffs', 'playoffTeamCount', 'playoffData', 'playoffDivisionDetails'],
          description: 'Adds playoff configuration to a league. If split league/playoff divisions is off, league standings feed one playoff bracket configuration. If split league/playoff divisions is on, league division placements must map into separate playoff divisions.',
        },
        {
          path: 'maxParticipants',
          label: 'Max Teams / Max Participants / Default Max Teams / Default Max Participants',
          inputType: 'number input',
          visibleWhen: visibleAlways,
          requiredWhen: 'Always required; minimum 2.',
          defaultOrPreset: 'Existing maxParticipants, otherwise blank/null until entered. Division defaults use this value when created.',
          createsOrUpdates: ['maxParticipants', 'divisionDetails[].maxParticipants'],
          description: 'Sets event-level capacity. If teamSignup is on, this means teams; otherwise it means individual participants. If singleDivision is off, the field acts as the default capacity for new divisions and each division can override it.',
        },
        {
          path: 'teamSignup',
          label: 'Use teams',
          inputType: 'checkbox',
          visibleWhen: 'Editable for Event and Weekly Event. League and Tournament show a fixed team-event state instead.',
          requiredWhen: 'Forced true for League and Tournament.',
          defaultOrPreset: 'Existing teamSignup. League and Tournament normalize it to true.',
          createsOrUpdates: ['teamSignup', 'teamSizeLimit', 'teams', 'players', 'freeAgentIds'],
          description: 'Determines whether registration is team-based or individual-based. Team events interpret maxParticipants as teams and use teamSizeLimit. Turning it on prevents the event creator from also joining as an individual participant in create mode.',
        },
        {
          path: 'leagueData.playoffTeamCount',
          label: 'Playoff Team Count / Default Playoff Team Count',
          inputType: 'number input',
          visibleWhen: 'Only visible for League events when playoffs are enabled.',
          requiredWhen: 'Required when playoffs are enabled and singleDivision is true. Used only as a default when singleDivision is false.',
          defaultOrPreset: 'Unset by default until explicitly chosen. The form intentionally does not silently choose a playoff team count.',
          createsOrUpdates: ['playoffTeamCount', 'divisionDetails[].playoffTeamCount'],
          description: 'Defines how many teams qualify for playoffs. In single-division leagues this value is saved on the league. In multi-division leagues it seeds new divisions but each division must have its own playoff team count.',
        },
        {
          path: 'teamSizeLimit',
          label: 'Team Size Limit',
          inputType: 'number input',
          visibleWhen: visibleAlways,
          requiredWhen: 'Always required; minimum 1.',
          defaultOrPreset: 'Existing teamSizeLimit, otherwise blank/null until entered.',
          createsOrUpdates: ['teamSizeLimit'],
          description: 'Maximum roster size per team for team-based events. It is still required by the form model for all event types so registration logic has a consistent capacity constraint.',
        },
        {
          path: 'start',
          label: 'Start Date & Time',
          inputType: 'date-time picker',
          visibleWhen: visibleAlways,
          requiredWhen: 'Always required.',
          defaultOrPreset: 'Existing start or create-flow default. Date picker cannot choose before today.',
          createsOrUpdates: ['start', 'timeSlots[].startDate', 'division age cutoff reference'],
          description: 'The event start datetime. It anchors event visibility, age-division cutoff fallback, recurring timeslot start windows, and the first available schedule/session date. For repeating timeslots, this is used as the default slot start boundary when the slot has no override.',
        },
        {
          path: 'end',
          label: 'End Date & Time',
          inputType: 'date-time picker',
          visibleWhen: 'Visible for Event and for schedulable event types that support open-ended scheduling.',
          requiredWhen: 'Required when noFixedEndDateTime is false. Must be after start.',
          defaultOrPreset: 'Existing end or create-flow default. Disabled when noFixedEndDateTime is true or rental slots lock the schedule.',
          createsOrUpdates: ['end', 'timeSlots[].endDate'],
          description: 'The fixed event end boundary. For leagues, tournaments, and weekly parent events, it can bound recurring timeslot generation. If open-ended scheduling is enabled, the scheduler can extend past this displayed end and repeating slots do not force an end boundary.',
        },
        {
          path: 'noFixedEndDateTime',
          label: 'No fixed end datetime scheduling',
          inputType: 'checkbox',
          visibleWhen: 'Visible for schedulable event types: League, Tournament, and parent Weekly Event.',
          requiredWhen: 'Optional. Disabled for externally rented/locked slots.',
          defaultOrPreset: 'Automatically enabled for new non-rental schedulable events. Forced off when external rental fields lock the schedule.',
          createsOrUpdates: ['noFixedEndDateTime', 'end'],
          description: 'Allows schedule generation to extend beyond the displayed end date/time instead of enforcing a fixed end. Turning it off requires a valid event end and causes recurring slot payloads to include the event end as their boundary.',
        },
        {
          path: 'location, address, coordinates',
          label: 'Location',
          inputType: 'location selector',
          visibleWhen: visibleAlways,
          requiredWhen: 'Location and coordinates are required.',
          defaultOrPreset: 'Uses existing location/address/coordinates. If missing, defaultLocation can prefill them. Coordinates may reverse-geocode to a city/state label on create.',
          createsOrUpdates: ['location', 'address', 'coordinates'],
          description: 'Sets the physical place for the event. The user-facing label is stored as location, the street/address detail as address, and longitude/latitude as coordinates. Coordinates are what validation checks to ensure the location is usable.',
        },
        {
          path: 'price',
          label: 'Price / Default Price',
          inputType: 'currency cents input',
          visibleWhen: visibleAlways,
          requiredWhen: 'Always normalized; defaults to 0 when billing is unavailable.',
          defaultOrPreset: 'Existing price in cents. Disabled until Stripe billing is available for the user or organization.',
          createsOrUpdates: ['price', 'divisionDetails[].price'],
          description: 'Event-level registration price in cents before displayed fee previews. If singleDivision is off, this becomes the default price for new divisions while existing divisions can have separate prices. Without Stripe, paid prices are not serialized.',
        },
        {
          path: 'requiredTemplateIds',
          label: 'Required Documents',
          inputType: 'multi-select',
          visibleWhen: 'Visible when document templates can be loaded for the organization/template organization context.',
          requiredWhen: 'Optional.',
          defaultOrPreset: 'Existing requiredTemplateIds, immutable rental/template requirements, or empty.',
          createsOrUpdates: ['requiredTemplateIds'],
          description: 'Selects document templates that registrants must complete for this event or rental/session. Templates are enforced by registration and signing flows, not by the schedule generator.',
        },
        {
          path: 'minAge',
          label: 'Minimum Age',
          inputType: 'number input',
          visibleWhen: visibleAlways,
          requiredWhen: 'Optional; must be <= maxAge when both are set.',
          defaultOrPreset: 'Existing minAge or blank.',
          createsOrUpdates: ['minAge'],
          description: 'Lower age eligibility boundary for registration. Age checks rely on user profile dates of birth, and hosts are still responsible for verification at check-in when needed.',
        },
        {
          path: 'maxAge',
          label: 'Maximum Age',
          inputType: 'number input',
          visibleWhen: visibleAlways,
          requiredWhen: 'Optional; must be >= minAge when both are set.',
          defaultOrPreset: 'Existing maxAge or blank.',
          createsOrUpdates: ['maxAge'],
          description: 'Upper age eligibility boundary for registration. Leave blank with Minimum Age if anyone can register.',
        },
        {
          path: 'cancellationRefundHours',
          label: 'Refund Cutoff (Hours)',
          inputType: 'number input',
          visibleWhen: visibleAlways,
          requiredWhen: 'Optional. Null disables automatic refunds; when enabled, minimum 0.',
          defaultOrPreset: 'Existing value, otherwise disabled.',
          createsOrUpdates: ['cancellationRefundHours'],
          description: 'How many hours before the event/session a cancellation can remain eligible for automatic refund handling. Zero means automatic refunds remain available until event start.',
        },
        {
          path: 'registrationCutoffHours',
          label: 'Registration Cutoff (Hours)',
          inputType: 'number input',
          visibleWhen: visibleAlways,
          requiredWhen: 'Always present; minimum 0.',
          defaultOrPreset: 'Existing value, otherwise 2.',
          createsOrUpdates: ['registrationCutoffHours'],
          description: 'How many hours before start/session time registration should close. For weekly parent events, this applies to each occurrence.',
        },
        {
          path: 'allowPaymentPlans',
          label: 'Payment Plans / Default Payment Plan',
          inputType: 'switch',
          visibleWhen: visibleAlways,
          requiredWhen: 'Optional and disabled without Stripe billing.',
          defaultOrPreset: 'Existing allowPaymentPlans or false.',
          createsOrUpdates: ['allowPaymentPlans', 'installmentCount', 'installmentAmounts', 'installmentDueDates', 'installmentDueRelativeDays'],
          description: 'Enables installments for the event-level price or as defaults for new divisions. The event price is updated from the sum of installment amounts. Weekly parent events use due-date offsets relative to each session date; other event types use absolute due datetimes.',
        },
        {
          path: 'installmentCount',
          label: 'Installments / Default Installments',
          inputType: 'number input',
          visibleWhen: 'Visible when allowPaymentPlans is enabled.',
          requiredWhen: 'Required when payment plans are enabled; must match number of installment amounts.',
          defaultOrPreset: 'Existing installmentCount or the number of existing installmentAmounts. Enabling payment plans creates at least one installment.',
          createsOrUpdates: ['installmentCount', 'installmentAmounts', 'installmentDueDates', 'installmentDueRelativeDays'],
          description: 'Controls how many installment rows exist. Changing it adds/removes matching due-date and amount entries.',
        },
        {
          path: 'installmentDueDates[] / installmentDueRelativeDays[]',
          label: 'Installment due / Installment due date offset',
          inputType: 'date-time picker or number input',
          visibleWhen: 'Visible for each payment-plan installment.',
          requiredWhen: 'Required when payment plans are enabled. Weekly parent events require offsets; other event types require due dates if due dates are supplied.',
          defaultOrPreset: 'Absolute due dates default to the event start when a row is created. Weekly offsets default to 0, meaning session day.',
          createsOrUpdates: ['installmentDueDates', 'installmentDueRelativeDays'],
          description: 'Sets when each installment is due. For parent weekly events, 0 means the session day, negative values mean days before the session, and positive values mean days after the session. This lets one plan apply across multiple recurring sessions.',
        },
        {
          path: 'installmentAmounts[]',
          label: 'Amount',
          inputType: 'currency cents input',
          visibleWhen: 'Visible for each payment-plan installment.',
          requiredWhen: 'Required when payment plans are enabled.',
          defaultOrPreset: 'Existing amounts or generated blank/zero rows when installment count changes.',
          createsOrUpdates: ['installmentAmounts'],
          description: 'The amount charged for each installment, stored in cents. The form displays a running total and updates the event/default price from that total.',
        },
        {
          path: 'allowTeamSplitDefault',
          label: 'Allow team bill splitting by default',
          inputType: 'switch',
          visibleWhen: 'Visible inside event/default payment plans when teamSignup is true.',
          requiredWhen: 'Optional.',
          defaultOrPreset: 'Existing allowTeamSplitDefault or false.',
          createsOrUpdates: ['allowTeamSplitDefault'],
          description: 'Sets whether team bills should default to being split among team members for team registrations. It is a billing default and does not affect bracket or schedule generation.',
        },
        {
          path: 'selectedFieldIds',
          label: 'Resources',
          inputType: 'facility-grouped multi-select',
          visibleWhen: 'Visible in Event Details for organization-managed simple events that require direct resource selection.',
          requiredWhen: 'Required when the organization/event type requires field selection.',
          defaultOrPreset: 'Existing fieldIds filtered to available organization resources, including locked rented resources, otherwise empty.',
          createsOrUpdates: ['fieldIds', 'selectedFieldIds'],
          description: 'Chooses which organization resources the event can use. Facilities expand to reveal their resources, including rented facilities when present. For league/tournament/weekly scheduling, resources are usually selected inside each timeslot instead.',
        },
        {
          path: 'fieldCount',
          label: 'Number of Resources',
          inputType: 'select',
          visibleWhen: 'Visible for personal/local-field events when the form manages local event fields and no external rental field locks them.',
          requiredWhen: 'At least 1.',
          defaultOrPreset: 'Existing number of resources or fieldCount, otherwise 1.',
          createsOrUpdates: ['fieldCount', 'fields'],
          description: 'Controls how many local event resources are provisioned for non-organization events. Increasing the count creates additional resource rows named Field N until renamed.',
        },
        {
          path: 'fields[].name',
          label: 'Field Name',
          inputType: 'text input',
          visibleWhen: 'Visible for each local field when fieldCount/local fields are managed by this form.',
          requiredWhen: 'Optional in the UI but used as the displayed field label.',
          defaultOrPreset: 'Existing field names or generated Field 1, Field 2, etc.',
          createsOrUpdates: ['fields', 'fieldIds'],
          description: 'Human-readable label for a locally-created field/court/surface. These fields become the selectable schedule resources for matches and timeslots.',
        },
      ],
    },
    {
      id: 'match-rules',
      title: 'Match Rules',
      visibleWhen: 'Visible for League and Tournament events. Hidden for simple Event and Weekly Event.',
      summary: 'Event-specific overrides for sport-supported result paths and incident capture behavior.',
      inputs: [
        {
          path: 'matchRulesOverride.supportsOvertime',
          label: 'Allow overtime',
          inputType: 'switch',
          visibleWhen: 'Only visible when the sport template supports overtime.',
          requiredWhen: 'Optional.',
          defaultOrPreset: 'Sport template value unless overridden.',
          createsOrUpdates: ['matchRulesOverride.supportsOvertime'],
          description: 'Marks overtime as an allowed result path for this event. If set to the sport default, the override is removed to keep the event using the template.',
        },
        {
          path: 'matchRulesOverride.supportsShootout',
          label: 'Allow shootout / tiebreak',
          inputType: 'switch',
          visibleWhen: 'Only visible when the sport template supports shootout/tiebreak.',
          requiredWhen: 'Optional.',
          defaultOrPreset: 'Sport template value unless overridden.',
          createsOrUpdates: ['matchRulesOverride.supportsShootout'],
          description: 'Enables a final tiebreak path for matches. When shootout is enabled, draw support is suppressed in resolved rules.',
        },
        {
          path: 'matchRulesOverride.supportedIncidentTypes',
          label: 'Incident types available in matches',
          inputType: 'multi-select',
          visibleWhen: 'Visible in Match Rules for League and Tournament.',
          requiredWhen: 'Optional; blank/default uses sport/default incident types.',
          defaultOrPreset: 'Default options are POINT, DISCIPLINE, NOTE, and ADMIN plus sport/event-supported types.',
          createsOrUpdates: ['matchRulesOverride.supportedIncidentTypes'],
          description: 'Controls which manual incident categories officials can add while scoring. If automatic point incidents are enabled, the point incident type is kept available.',
        },
        {
          path: 'autoCreatePointMatchIncidents',
          label: 'Create a scoring incident for each point / goal',
          inputType: 'switch',
          visibleWhen: 'Visible in Match Rules for League and Tournament.',
          requiredWhen: 'Optional.',
          defaultOrPreset: 'Existing autoCreatePointMatchIncidents or false.',
          createsOrUpdates: ['autoCreatePointMatchIncidents'],
          description: 'When on, officials are prompted to identify the player before each score change, creating point/goal incidents automatically. When off, officials can still add incidents manually if the type is available.',
        },
      ],
    },
    {
      id: 'staff',
      title: 'Staff',
      visibleWhen: visibleAlways,
      summary: 'Hosts, assistant hosts, officials, official positions, team-officiating behavior, and scheduler staffing constraints.',
      inputs: [
        {
          path: 'doTeamsOfficiate',
          label: 'Teams provide officials',
          inputType: 'switch',
          visibleWhen: visibleAlways,
          requiredWhen: 'Optional.',
          defaultOrPreset: 'Existing doTeamsOfficiate or false.',
          createsOrUpdates: ['doTeamsOfficiate', 'teamOfficialsMaySwap'],
          description: 'Allows assigning participating teams as match officials in addition to dedicated staff officials. Turning it off also turns off teamOfficialsMaySwap.',
        },
        {
          path: 'teamOfficialsMaySwap',
          label: 'Team officials may swap',
          inputType: 'switch',
          visibleWhen: 'Visible only when Teams provide officials is enabled.',
          requiredWhen: 'Optional.',
          defaultOrPreset: 'Existing value only if doTeamsOfficiate is true; otherwise false.',
          createsOrUpdates: ['teamOfficialsMaySwap'],
          description: 'Allows any participating team to take over officiating a match. This affects match staffing flexibility, not team registration.',
        },
        {
          path: 'officialSchedulingMode',
          label: 'Official scheduling mode',
          inputType: 'select',
          visibleWhen: visibleAlways,
          requiredWhen: 'Always normalized to STAFFING, TEAM_STAFFING, SCHEDULE, or OFF.',
          defaultOrPreset: 'Existing mode normalized from NONE to OFF; otherwise SCHEDULE.',
          createsOrUpdates: ['officialSchedulingMode'],
          description: 'Controls how strictly the scheduler uses officials. STAFFING requires every match to be fully staffed with assigned officials and no conflicts. TEAM_STAFFING requires a conflict-free team official without assigned-official coverage. SCHEDULE allows matches even if not fully staffed. OFF means fully staffed matches are expected but conflicts are allowed.',
        },
        {
          path: 'officialPositions[]',
          label: 'Official Positions: Position and Count',
          inputType: 'repeatable text and number inputs',
          visibleWhen: visibleAlways,
          requiredWhen: 'Each configured position needs a non-empty name and count >= 1.',
          defaultOrPreset: 'Existing event positions, otherwise seeded from sport officialPositionTemplates when available. Load sport defaults resets from sport templates.',
          createsOrUpdates: ['officialPositions', 'eventOfficials[].positionIds'],
          description: 'Defines the event-specific official roles and how many of each role each match needs. Sport defaults only seed the list; event edits are saved on the event and used by the scheduler and official eligibility controls.',
        },
        {
          path: 'hostId',
          label: 'Set as host',
          inputType: 'staff action button',
          visibleWhen: 'Visible in organization staff search results for organization-hosted events.',
          requiredWhen: 'A host is required by payload fallback; current user is used if no explicit host is set.',
          defaultOrPreset: 'Existing hostId or current user on create.',
          createsOrUpdates: ['hostId'],
          description: 'Assigns the primary host for the event. Organization assignment is sanitized so only allowed organization staff/owners can become host.',
        },
        {
          path: 'assistantHostIds',
          label: 'Add as assistant / Add as assistant host',
          inputType: 'staff action button',
          visibleWhen: 'Visible in organization staff or non-organization user search.',
          requiredWhen: 'Optional.',
          defaultOrPreset: 'Existing assistantHostIds or empty.',
          createsOrUpdates: ['assistantHostIds', 'pendingStaffInvites[]'],
          description: 'Adds host-side staff who can help manage the event. Assistant hosts can be existing users or staged email invites, depending on the event context.',
        },
        {
          path: 'officialIds',
          label: 'Add as official',
          inputType: 'staff action button',
          visibleWhen: 'Visible in organization staff or non-organization user search.',
          requiredWhen: 'Optional unless STAFFING mode requires enough active officials. Not required for TEAM_STAFFING.',
          defaultOrPreset: 'Existing officialIds or empty.',
          createsOrUpdates: ['officialIds', 'officials', 'eventOfficials', 'pendingStaffInvites[]'],
          description: 'Adds a person to the official pool for the event. Organization-hosted events search the organization roster; personal events search users or stage email invites.',
        },
        {
          path: 'organizationStaffSearch, organizationStaffTypeFilter, organizationStaffStatusFilter',
          label: 'Search staff / Role filter / Status filter',
          inputType: 'text input and selects',
          visibleWhen: 'Visible only for organization-hosted events.',
          requiredWhen: 'Optional filtering controls.',
          defaultOrPreset: 'Search starts empty; filters default to all roles and all statuses.',
          createsOrUpdates: [],
          description: 'Filters organization roster cards so staff can be assigned as host, assistant host, or official. These controls do not serialize directly; the assignment buttons do.',
        },
        {
          path: 'nonOrgStaffSearch',
          label: 'Search users',
          inputType: 'text input',
          visibleWhen: 'Visible only for non-organization-hosted events.',
          requiredWhen: 'Optional. Search requires at least 2 characters.',
          defaultOrPreset: 'Empty.',
          createsOrUpdates: [],
          description: 'Finds existing users by name or username so they can be added as officials or assistant hosts. The search text itself is not saved.',
        },
        {
          path: 'pendingStaffInvites[]',
          label: 'Invite by email: First name, Last name, Email, Official, Assistant host',
          inputType: 'repeatable text inputs and role buttons',
          visibleWhen: 'Visible for non-organization-hosted events.',
          requiredWhen: 'An invite needs a valid email and at least one role before it can be staged.',
          defaultOrPreset: 'Empty pending invite form. Existing pending invites can be preserved in form state.',
          createsOrUpdates: ['pendingStaffInvites', 'officialIds', 'assistantHostIds after invite save'],
          description: 'Stages email invitations for staff who are not existing users or are not found by search. Invite cards remain labeled Email invite until the event is saved and pending invites are submitted.',
        },
        {
          path: 'eventOfficials[].positionIds',
          label: 'Eligible positions',
          inputType: 'multi-select',
          visibleWhen: 'Visible for assigned active officials.',
          requiredWhen: 'Clearable is false; used by scheduler coverage checks.',
          defaultOrPreset: 'Existing eligibility or generated defaults from official positions.',
          createsOrUpdates: ['eventOfficials[].positionIds'],
          description: 'Restricts which configured official positions a specific official can cover. The scheduler uses this when assigning officials in STAFFING or SCHEDULE mode.',
        },
        {
          path: 'eventOfficials[].fieldIds',
          label: 'Eligible fields',
          inputType: 'multi-select',
          visibleWhen: 'Visible for assigned active officials when event fields are available.',
          requiredWhen: 'Optional. Empty means the official can work all event fields.',
          defaultOrPreset: 'Existing field eligibility or empty.',
          createsOrUpdates: ['eventOfficials[].fieldIds'],
          description: 'Restricts an official to specific fields/courts. Leave empty to allow assignments on any event field.',
        },
      ],
    },
    {
      id: 'division-settings',
      title: 'Divisions',
      visibleWhen: visibleAlways,
      summary: 'Participant grouping, division pricing/capacity, per-division payment plans, playoff qualification counts, and split playoff division mapping.',
      inputs: [
        {
          path: 'divisionEditor.gender',
          label: 'Gender',
          inputType: 'select',
          visibleWhen: visibleAlways,
          requiredWhen: 'Required before adding/updating a division.',
          defaultOrPreset: 'Defaults from selected division or sport fallback.',
          createsOrUpdates: ['divisionDetails[].gender', 'divisionDetails[].key', 'divisions'],
          description: 'Part of the division identity. Available values are Mens, Womens, and CoEd. It contributes to the generated division token and display name.',
        },
        {
          path: 'divisionEditor.skillDivisionTypeId',
          label: 'Skill Division',
          inputType: 'select',
          visibleWhen: visibleAlways,
          requiredWhen: 'Required before adding/updating a division.',
          defaultOrPreset: 'Sport-specific skill division default, usually Open.',
          createsOrUpdates: ['divisionDetails[].skillDivisionTypeId', 'divisionDetails[].skillDivisionTypeName', 'divisionDetails[].divisionTypeId'],
          description: 'Selects the sport-specific skill/rating bucket for the division. Combined with age division to create the composite division type saved on the event.',
        },
        {
          path: 'divisionEditor.ageDivisionTypeId',
          label: 'Age Division',
          inputType: 'select',
          visibleWhen: visibleAlways,
          requiredWhen: 'Required before adding/updating a division.',
          defaultOrPreset: 'Sport-specific age division default, usually 18+.',
          createsOrUpdates: ['divisionDetails[].ageDivisionTypeId', 'divisionDetails[].ageDivisionTypeName', 'divisionDetails[].ageCutoffDate'],
          description: 'Selects the age grouping for the division. The form applies sport age cutoff defaults using the event start date as reference when needed.',
        },
        {
          path: 'divisionEditor.name',
          label: 'Division Name',
          inputType: 'text input',
          visibleWhen: visibleAlways,
          requiredWhen: 'Required before adding/updating a division; max 160 characters.',
          defaultOrPreset: 'Auto-generated from gender plus skill/age selections until the user edits it.',
          createsOrUpdates: ['divisionDetails[].name'],
          description: 'The display label shown to hosts and registrants. Editing it customizes the label without changing the underlying skill/age/gender selections.',
        },
        {
          path: 'divisionEditor.price',
          label: 'Division Price',
          inputType: 'currency cents input',
          visibleWhen: visibleAlways,
          requiredWhen: 'Normalized to 0 or more. Disabled when singleDivision is on or Stripe is unavailable.',
          defaultOrPreset: 'Defaults from event price for new divisions.',
          createsOrUpdates: ['divisionDetails[].price'],
          description: 'Per-division registration price. When singleDivision is enabled, division price mirrors the event-level price and cannot be edited separately.',
        },
        {
          path: 'divisionEditor.maxParticipants',
          label: 'Division Max Teams / Division Max Participants',
          inputType: 'number input',
          visibleWhen: visibleAlways,
          requiredWhen: 'Required before saving multi-division events; minimum 2.',
          defaultOrPreset: 'Defaults from event maxParticipants for new divisions.',
          createsOrUpdates: ['divisionDetails[].maxParticipants'],
          description: 'Capacity for this specific division. When singleDivision is enabled, division capacity mirrors the event-level maxParticipants and cannot be edited separately.',
        },
        {
          path: 'divisionEditor.playoffTeamCount',
          label: 'Division Playoff Team Count',
          inputType: 'number input',
          visibleWhen: 'Visible for League events. Enabled only when playoffs are enabled and singleDivision is off.',
          requiredWhen: 'Required for each league division when playoffs are enabled and singleDivision is off.',
          defaultOrPreset: 'Defaults from the event/default playoff team count for new divisions when present; otherwise unset.',
          createsOrUpdates: ['divisionDetails[].playoffTeamCount'],
          description: 'How many teams from this division qualify for playoffs. Required per division for multi-division playoff leagues.',
        },
        {
          path: 'divisionEditor.allowPaymentPlans',
          label: 'Division Payment Plan',
          inputType: 'switch',
          visibleWhen: 'Visible when singleDivision is off.',
          requiredWhen: 'Optional and disabled without Stripe billing.',
          defaultOrPreset: 'Defaults from event-level payment plan values for new divisions when configured.',
          createsOrUpdates: ['divisionDetails[].allowPaymentPlans', 'divisionDetails[].installmentCount', 'divisionDetails[].installmentAmounts'],
          description: 'Enables installments for only the selected division. Single-division events use event-level payment plans instead.',
        },
        {
          path: 'divisionEditor.installmentCount',
          label: 'Division Installments',
          inputType: 'number input',
          visibleWhen: 'Visible when a division payment plan is enabled.',
          requiredWhen: 'Required when division payment plan is enabled; must match number of amounts.',
          defaultOrPreset: 'Existing division installmentCount or number of division installment amounts.',
          createsOrUpdates: ['divisionDetails[].installmentCount', 'divisionDetails[].installmentAmounts'],
          description: 'Controls the number of installment rows for this division-specific payment plan.',
        },
        {
          path: 'divisionEditor.installmentDueDates[] / divisionEditor.installmentDueRelativeDays[]',
          label: 'Division installment due / due date offset',
          inputType: 'date-time picker or number input',
          visibleWhen: 'Visible for each division installment.',
          requiredWhen: 'Required when division payment plan is enabled; weekly parent events use offsets.',
          defaultOrPreset: 'Absolute due dates default to event start; weekly offsets default to 0.',
          createsOrUpdates: ['divisionDetails[].installmentDueDates', 'divisionDetails[].installmentDueRelativeDays'],
          description: 'Due timing for division-specific installments. Parent weekly events use relative offsets from each session date, matching event-level payment-plan behavior.',
        },
        {
          path: 'divisionEditor.installmentAmounts[]',
          label: 'Division installment Amount',
          inputType: 'currency cents input',
          visibleWhen: 'Visible for each division installment.',
          requiredWhen: 'Required when division payment plan is enabled.',
          defaultOrPreset: 'Existing division amounts or generated rows.',
          createsOrUpdates: ['divisionDetails[].installmentAmounts'],
          description: 'Amount charged for each installment of the selected division. The form updates the division price from the installment total.',
        },
        {
          path: 'divisions / divisionDetails',
          label: 'Add Division / Update Division / Edit / Remove',
          inputType: 'buttons and division list',
          visibleWhen: visibleAlways,
          requiredWhen: 'At least one division is required.',
          defaultOrPreset: 'Generated from sport defaults when no saved divisions exist.',
          createsOrUpdates: ['divisions', 'divisionDetails'],
          description: 'Persists division rows and keeps the event divisions array in sync with detailed division records. Removing a division also affects timeslot division options and playoff placement mapping.',
        },
        {
          path: 'singleDivision',
          label: 'Single Division (all skill levels play together)',
          inputType: 'switch',
          visibleWhen: 'Visible for Event, Weekly Event, League, and Tournament. League/Tournament also show fixed team-event context.',
          requiredWhen: 'Always present.',
          defaultOrPreset: 'Often forced true when selecting League or Tournament. Existing value is used when editing.',
          createsOrUpdates: ['singleDivision', 'divisionDetails', 'timeSlots[].divisions'],
          description: 'When enabled, all participants/teams play together for scheduling and pricing/capacity mirror event-level values. Every timeslot is automatically assigned all selected divisions.',
        },
        {
          path: 'registrationByDivisionType',
          label: 'Register by Division Type',
          inputType: 'switch',
          visibleWhen: 'Visible with divisions for supported event/team settings.',
          requiredWhen: 'Optional.',
          defaultOrPreset: 'Existing registrationByDivisionType or false.',
          createsOrUpdates: ['registrationByDivisionType'],
          description: 'Lets users choose a division type during registration and be auto-assigned to a matching concrete division. This is useful when multiple concrete divisions share type semantics.',
        },
        {
          path: 'splitLeaguePlayoffDivisions',
          label: 'Split League & Playoff Divisions',
          inputType: 'switch',
          visibleWhen: 'Only visible for League events in the fixed team-event settings area.',
          requiredWhen: 'Optional, but if enabled it makes playoff divisions and placement mapping required.',
          defaultOrPreset: 'Existing value. Disabled unless playoffs are enabled. Auto-disabled when singleDivision is enabled, except external rental field cases.',
          createsOrUpdates: ['splitLeaguePlayoffDivisions', 'playoffDivisionDetails', 'divisionDetails[].playoffPlacementDivisionIds'],
          description: 'Separates regular-season league divisions from playoff bracket divisions. When enabled, each qualifying placement from each league division must map to a configured playoff division.',
        },
        {
          path: 'divisionDetails[].playoffPlacementDivisionIds[]',
          label: 'Placement #N',
          inputType: 'select',
          visibleWhen: 'Visible on league division cards when playoffs and split league/playoff divisions are enabled.',
          requiredWhen: 'Required for every placement up to the division playoffTeamCount.',
          defaultOrPreset: 'Existing mapping or blank until selected.',
          createsOrUpdates: ['divisionDetails[].playoffPlacementDivisionIds'],
          description: 'Maps each regular-season placement to a playoff division. For example, placement 1 and 2 could feed a Gold playoff division while lower placements feed Silver.',
        },
        {
          path: 'playoffDivisionDetails[]',
          label: 'Playoff Division Name / Teams Count / Participants Count / Add Playoff Division',
          inputType: 'repeatable text, number, and buttons',
          visibleWhen: 'Visible only when League playoffs and split league/playoff divisions are enabled.',
          requiredWhen: 'At least one playoff division is required when split playoffs are enabled. Each playoff division needs name and capacity >= 2.',
          defaultOrPreset: 'When enabling split playoffs, the form creates one playoff division if none exist.',
          createsOrUpdates: ['playoffDivisionDetails'],
          description: 'Defines the playoff bracket containers that league placements feed into. Capacity limits how many mapped placements can enter that playoff division.',
        },
      ],
    },
    {
      id: 'league-scoring-config',
      title: 'League Scoring Config',
      visibleWhen: 'Visible only for League events.',
      summary: 'Numeric standings rules applied automatically to league standings. The sport controls which scoring fields are shown.',
      inputs: [
        {
          path: 'leagueScoringConfig.pointsForWin',
          label: 'Points for Win',
          inputType: 'number input',
          visibleWhen: 'Visible when sport.usePointsForWin is true, or when no sport flag data is available.',
          requiredWhen: 'Always numeric when visible.',
          defaultOrPreset: 'Existing leagueScoringConfig value or 0.',
          createsOrUpdates: ['leagueScoringConfig.pointsForWin'],
          description: 'Standings points awarded for a match win.',
        },
        {
          path: 'leagueScoringConfig.pointsForDraw',
          label: 'Points for Draw',
          inputType: 'number input',
          visibleWhen: 'Visible when sport.usePointsForDraw is true, or when no sport flag data is available.',
          requiredWhen: 'Always numeric when visible.',
          defaultOrPreset: 'Existing value or 0.',
          createsOrUpdates: ['leagueScoringConfig.pointsForDraw'],
          description: 'Standings points awarded for a draw/tie when the sport and match rules support draws.',
        },
        {
          path: 'leagueScoringConfig.pointsForLoss',
          label: 'Points for Loss',
          inputType: 'number input',
          visibleWhen: 'Visible when sport.usePointsForLoss is true, or when no sport flag data is available.',
          requiredWhen: 'Always numeric when visible.',
          defaultOrPreset: 'Existing value or 0.',
          createsOrUpdates: ['leagueScoringConfig.pointsForLoss'],
          description: 'Standings points awarded for a loss.',
        },
        {
          path: 'leagueScoringConfig.pointsPerSetWin',
          label: 'Points per Set Win',
          inputType: 'number input',
          visibleWhen: 'Visible when sport.usePointsPerSetWin is true, or when no sport flag data is available.',
          requiredWhen: 'Always numeric when visible.',
          defaultOrPreset: 'Existing value or 0.',
          createsOrUpdates: ['leagueScoringConfig.pointsPerSetWin'],
          description: 'Additional standings points per set won in set-based leagues.',
        },
        {
          path: 'leagueScoringConfig.pointsPerSetLoss',
          label: 'Points per Set Loss',
          inputType: 'number input',
          visibleWhen: 'Visible when sport.usePointsPerSetLoss is true, or when no sport flag data is available.',
          requiredWhen: 'Always numeric when visible.',
          defaultOrPreset: 'Existing value or 0.',
          createsOrUpdates: ['leagueScoringConfig.pointsPerSetLoss'],
          description: 'Additional standings points per set lost in set-based leagues.',
        },
        {
          path: 'leagueScoringConfig.pointsPerGameWin',
          label: 'Points per Game Win',
          inputType: 'number input',
          visibleWhen: 'Visible when sport.usePointsPerGameWin is true, or when no sport flag data is available.',
          requiredWhen: 'Always numeric when visible.',
          defaultOrPreset: 'Existing value or 0.',
          createsOrUpdates: ['leagueScoringConfig.pointsPerGameWin'],
          description: 'Additional standings points per game won when the sport uses game-level scoring.',
        },
        {
          path: 'leagueScoringConfig.pointsPerGameLoss',
          label: 'Points per Game Loss',
          inputType: 'number input',
          visibleWhen: 'Visible when sport.usePointsPerGameLoss is true, or when no sport flag data is available.',
          requiredWhen: 'Always numeric when visible.',
          defaultOrPreset: 'Existing value or 0.',
          createsOrUpdates: ['leagueScoringConfig.pointsPerGameLoss'],
          description: 'Additional standings points per game lost when the sport uses game-level scoring.',
        },
        {
          path: 'leagueScoringConfig.pointsPerGoalScored',
          label: 'Points per Goal Scored',
          inputType: 'number input',
          visibleWhen: 'Visible when sport.usePointsPerGoalScored is true, or when no sport flag data is available.',
          requiredWhen: 'Always numeric when visible.',
          defaultOrPreset: 'Existing value or 0.',
          createsOrUpdates: ['leagueScoringConfig.pointsPerGoalScored'],
          description: 'Goal-based points are displayed but not automatically applied to standings by the current panel note.',
        },
        {
          path: 'leagueScoringConfig.pointsPerGoalConceded',
          label: 'Points per Goal Conceded',
          inputType: 'number input',
          visibleWhen: 'Visible when sport.usePointsPerGoalConceded is true, or when no sport flag data is available.',
          requiredWhen: 'Always numeric when visible.',
          defaultOrPreset: 'Existing value or 0.',
          createsOrUpdates: ['leagueScoringConfig.pointsPerGoalConceded'],
          description: 'Goal-conceded points are displayed but not automatically applied to standings by the current panel note.',
        },
      ],
    },
    {
      id: 'schedule-config',
      title: 'Schedule',
      visibleWhen: 'Visible for League, Tournament, parent Weekly Event, weekly child sessions, and rental-slot contexts.',
      summary: 'Tournament bracket settings, league configuration, recurring/non-recurring timeslots, weekly session fields, and playoff bracket configuration.',
      inputs: [
        {
          path: 'selectedFieldIds',
          label: 'Session Resources',
          inputType: 'facility-grouped multi-select',
          visibleWhen: 'Only visible for older parent-linked weekly rows where eventType is WEEKLY_EVENT and parentEvent is set.',
          requiredWhen: 'Optional unless field selection is locked by the selected session. Disabled by immutable field settings.',
          defaultOrPreset: 'Inherited from selected weekly session/parent slot or saved child fieldIds.',
          createsOrUpdates: ['fieldIds', 'selectedFieldIds'],
          description: 'Chooses which resources an older parent-linked weekly row can use. New weekly registrations use the parent event slot and occurrence date instead of child session events.',
        },
        {
          path: 'tournamentData.doubleElimination',
          label: 'Tournament Format',
          inputType: 'select',
          visibleWhen: 'Visible for Tournament events and for playoff configuration panels.',
          requiredWhen: 'Always has a value.',
          defaultOrPreset: 'Single Elimination by default unless existing config is double elimination.',
          createsOrUpdates: ['doubleElimination', 'tournamentData.doubleElimination', 'playoffData.doubleElimination', 'playoffDivisionDetails[].playoffConfig.doubleElimination'],
          description: 'Chooses whether the bracket is single elimination or double elimination. Double elimination enables loser bracket set count and loser bracket points-to-victory controls for set-based sports.',
        },
        {
          path: 'tournamentData.restTimeMinutes',
          label: 'Rest Time Between Matches (minutes)',
          inputType: 'number input',
          visibleWhen: 'Visible for Tournament events and playoff configuration panels; League has its own restTimeMinutes input.',
          requiredWhen: 'Always numeric; minimum 0.',
          defaultOrPreset: 'Existing value or 0.',
          createsOrUpdates: ['restTimeMinutes', 'tournamentData.restTimeMinutes', 'playoffData.restTimeMinutes'],
          description: 'Minimum rest gap the scheduler inserts between matches for the same team in tournament or playoff bracket scheduling.',
        },
        {
          path: 'tournamentData.matchDurationMinutes',
          label: 'Match Duration (minutes)',
          inputType: 'number input',
          visibleWhen: 'Visible for Tournament events when the sport/config is not set-based and showDurationControls is true.',
          requiredWhen: 'Minimum 15 minutes when visible.',
          defaultOrPreset: 'Existing value or 60.',
          createsOrUpdates: ['matchDurationMinutes', 'usesSets'],
          description: 'Duration used to place each tournament match into timeslots for non-set-based sports.',
        },
        {
          path: 'tournamentData.setDurationMinutes',
          label: 'Set Duration (minutes)',
          inputType: 'number input',
          visibleWhen: 'Visible for set-based Tournament events when showDurationControls is true.',
          requiredWhen: 'Minimum 5 minutes when visible.',
          defaultOrPreset: 'Existing value or 20 when set mode is required.',
          createsOrUpdates: ['setDurationMinutes', 'usesSets'],
          description: 'Duration per set used to estimate schedule length for set-based tournament matches.',
        },
        {
          path: 'tournamentData.winnerSetCount',
          label: 'Winner Set Count',
          inputType: 'select',
          visibleWhen: 'Visible for set-based Tournament events and set-based playoff panels.',
          requiredWhen: 'Always one of Best of 1, Best of 3, or Best of 5 when visible.',
          defaultOrPreset: 'Existing value or Best of 1.',
          createsOrUpdates: ['winnerSetCount', 'winnerBracketPointsToVictory'],
          description: 'Number of sets required in the winner/main bracket. Changing it resizes winnerBracketPointsToVictory, filling new set targets with 21.',
        },
        {
          path: 'tournamentData.loserSetCount',
          label: 'Loser Set Count',
          inputType: 'select',
          visibleWhen: 'Visible for set-based double-elimination Tournament events and playoff panels.',
          requiredWhen: 'Always one of Best of 1, Best of 3, or Best of 5 when visible.',
          defaultOrPreset: 'Existing value or Best of 1.',
          createsOrUpdates: ['loserSetCount', 'loserBracketPointsToVictory'],
          description: 'Number of sets required in the loser bracket for double-elimination tournaments. Hidden for single elimination.',
        },
        {
          path: 'tournamentData.winnerBracketPointsToVictory[]',
          label: 'Winner Bracket Points to Victory: Set N',
          inputType: 'number input',
          visibleWhen: 'Visible for set-based Tournament events and playoff panels.',
          requiredWhen: 'Each visible set target is required; minimum 1.',
          defaultOrPreset: 'Existing values or 21 for each set.',
          createsOrUpdates: ['winnerBracketPointsToVictory'],
          description: 'Points needed to win each set in the winner/main bracket. The number of inputs follows winnerSetCount.',
        },
        {
          path: 'tournamentData.loserBracketPointsToVictory[]',
          label: 'Loser Bracket Points to Victory: Set N',
          inputType: 'number input',
          visibleWhen: 'Visible for set-based double-elimination Tournament events and playoff panels.',
          requiredWhen: 'Each visible set target is required; minimum 1.',
          defaultOrPreset: 'Existing values or 21 for each set.',
          createsOrUpdates: ['loserBracketPointsToVictory'],
          description: 'Points needed to win each set in the loser bracket. The number of inputs follows loserSetCount.',
        },
        {
          path: 'tournamentData.prize',
          label: 'Prize (Optional)',
          inputType: 'text input',
          visibleWhen: 'Visible for Tournament settings. Also present in playoff panels but playoff prize is usually not the scheduling-critical field.',
          requiredWhen: 'Optional.',
          defaultOrPreset: 'Existing prize or empty.',
          createsOrUpdates: ['prize'],
          description: 'Public prize/reward description for a tournament. It does not affect bracket generation or match scheduling.',
        },
        {
          path: 'leagueData.gamesPerOpponent',
          label: 'Games per Opponent',
          inputType: 'number input',
          visibleWhen: 'Visible in League Configuration for League events.',
          requiredWhen: 'Required; minimum 1.',
          defaultOrPreset: 'Existing value or 1.',
          createsOrUpdates: ['gamesPerOpponent'],
          description: 'How many times each team should play each opponent during league schedule generation.',
        },
        {
          path: 'leagueData.matchDurationMinutes',
          label: 'Match Duration (minutes)',
          inputType: 'number input',
          visibleWhen: 'Visible in League Configuration for non-set-based sports.',
          requiredWhen: 'Minimum 15 minutes when visible.',
          defaultOrPreset: 'Existing value or 60.',
          createsOrUpdates: ['matchDurationMinutes', 'usesSets'],
          description: 'Duration used by the league scheduler to fit each generated match into a timeslot for non-set-based sports.',
        },
        {
          path: 'leagueData.restTimeMinutes',
          label: 'Rest Time Between Matches (minutes)',
          inputType: 'number input',
          visibleWhen: 'Visible in League Configuration for League events.',
          requiredWhen: 'Required; minimum 0.',
          defaultOrPreset: 'Existing value or 0.',
          createsOrUpdates: ['restTimeMinutes'],
          description: 'Minimum rest gap between matches for the same team when the league scheduler builds the schedule.',
        },
        {
          path: 'leagueData.setsPerMatch',
          label: 'Sets per Match',
          inputType: 'select',
          visibleWhen: 'Visible in League Configuration for set-based sports.',
          requiredWhen: 'Best of 1, 3, or 5 when visible.',
          defaultOrPreset: 'Existing value or Best of 1.',
          createsOrUpdates: ['setsPerMatch', 'pointsToVictory', 'usesSets'],
          description: 'Controls how many sets are played per league match. Changing it resizes the Points to Victory inputs, filling new set targets with 21.',
        },
        {
          path: 'leagueData.setDurationMinutes',
          label: 'Set Duration (minutes)',
          inputType: 'number input',
          visibleWhen: 'Visible in League Configuration for set-based sports.',
          requiredWhen: 'Minimum 5 minutes when visible.',
          defaultOrPreset: 'Existing value or 20 when set mode is required.',
          createsOrUpdates: ['setDurationMinutes', 'usesSets'],
          description: 'Duration per set used to estimate total match length for set-based league scheduling.',
        },
        {
          path: 'leagueData.pointsToVictory[]',
          label: 'Points to Victory: Set N',
          inputType: 'number input',
          visibleWhen: 'Visible in League Configuration for set-based sports.',
          requiredWhen: 'Each visible set target is required; minimum 1.',
          defaultOrPreset: 'Existing values or 21 for each set.',
          createsOrUpdates: ['pointsToVictory'],
          description: 'Points needed to win each set in a league match. The number of inputs follows setsPerMatch.',
        },
        {
          path: 'leagueSlots',
          label: 'Weekly Timeslots',
          inputType: 'repeatable slot cards',
          visibleWhen: 'Visible for League, Tournament, and parent Weekly Event scheduling. Hidden for weekly child sessions and read-only for immutable/rental slots.',
          requiredWhen: 'At least one valid timeslot is required for schedulable event types.',
          defaultOrPreset: 'Existing timeSlots are merged into slot rows. If none exist, one empty slot row is created. Immutable/rental timeSlots are displayed as read-only or serialized without allowing schedule edits.',
          createsOrUpdates: ['timeSlots', 'timeSlotIds', 'fieldIds'],
          description: 'Defines when and where the scheduler can place matches for leagues and tournaments, and defines recurring sessions for parent weekly events. For weekly parent events, each selected day/time occurrence becomes a selectable session; sessions are represented as same-day start/end times and child weekly events are created from a selected occurrence when participants register or hosts manage that session. A single slot can cover multiple weekdays through daysOfWeek, which creates multiple weekly session occurrences using the same time range, fields, divisions, pricing/document constraints, and date window.',
        },
        {
          path: 'leagueSlots[].scheduledFieldIds',
          label: 'Timeslot Fields',
          inputType: 'searchable field checklist',
          visibleWhen: 'Visible inside each timeslot.',
          requiredWhen: 'At least one field is required per timeslot.',
          defaultOrPreset: 'Existing scheduledFieldIds or scheduledFieldId. For new slots, empty until selected.',
          createsOrUpdates: ['timeSlots[].scheduledFieldIds', 'timeSlots[].scheduledFieldId', 'fieldIds'],
          description: 'Selects which fields/courts the slot can use. The scheduler can place matches on any selected field during that slot. Holding Shift in the UI selects a range of fields. The first selected field is also stored as scheduledFieldId for legacy compatibility.',
        },
        {
          path: 'leagueSlots[].divisions',
          label: 'Timeslot Divisions',
          inputType: 'multi-select',
          visibleWhen: 'Visible inside each timeslot.',
          requiredWhen: 'Optional for multi-division events; singleDivision forces all event divisions.',
          defaultOrPreset: 'Defaults to all selected event divisions for new slots.',
          createsOrUpdates: ['timeSlots[].divisions'],
          description: 'Limits which divisions can be scheduled in the slot. When singleDivision is enabled, this is locked to all selected event divisions. When split playoffs are enabled, options can include league and playoff divisions so playoff-specific slots can be targeted.',
        },
        {
          path: 'leagueSlots[].repeating',
          label: 'Repeats weekly',
          inputType: 'switch',
          visibleWhen: 'Visible inside each timeslot.',
          requiredWhen: 'Always present; defaults true.',
          defaultOrPreset: 'Existing repeating value, otherwise true.',
          createsOrUpdates: ['timeSlots[].repeating'],
          description: 'Determines whether the slot recurs weekly inside the event date window or represents one explicit date/time block. Repeating slots use Days of Week plus start/end times. Non-repeating slots use explicit start and end datetimes.',
        },
        {
          path: 'leagueSlots[].daysOfWeek',
          label: 'Days of Week',
          inputType: 'multi-select',
          visibleWhen: 'Visible when Repeats weekly is on.',
          requiredWhen: 'At least one day is required for repeating slots.',
          defaultOrPreset: 'Existing daysOfWeek, falling back to dayOfWeek for legacy slots. New slots start empty.',
          createsOrUpdates: ['timeSlots[].daysOfWeek', 'timeSlots[].dayOfWeek'],
          description: 'Selects the weekdays when a repeating slot occurs. The form stores Monday as 0 through Sunday as 6. Multiple selected days are serialized on one slot row and create multiple weekly occurrences or scheduling windows with the same time range and field/division constraints.',
        },
        {
          path: 'leagueSlots[].startDate',
          label: 'Start Date Override',
          inputType: 'date picker',
          visibleWhen: 'Visible when Repeats weekly is on.',
          requiredWhen: 'Optional for repeating slots; if blank, event start is used.',
          defaultOrPreset: 'Existing slot startDate only when it differs from event start; otherwise blank in the form and serialized from event start.',
          createsOrUpdates: ['timeSlots[].startDate'],
          description: 'Optional date boundary for when this repeating slot begins. Leave blank to use the event start date. For weekly parent events, occurrences before this date are not available.',
        },
        {
          path: 'leagueSlots[].startTimeMinutes',
          label: 'Start Time',
          inputType: 'time input',
          visibleWhen: 'Visible when Repeats weekly is on.',
          requiredWhen: 'Required for repeating slots.',
          defaultOrPreset: 'Existing startTimeMinutes or blank for new slots.',
          createsOrUpdates: ['timeSlots[].startTimeMinutes'],
          description: 'Minute-of-day when the repeating slot starts. Stored as minutes after midnight and used to create match/session start datetimes on each selected weekday.',
        },
        {
          path: 'leagueSlots[].endTimeMinutes',
          label: 'End Time',
          inputType: 'time input',
          visibleWhen: 'Visible when Repeats weekly is on.',
          requiredWhen: 'Required for repeating slots and must be after Start Time.',
          defaultOrPreset: 'Existing endTimeMinutes or blank for new slots.',
          createsOrUpdates: ['timeSlots[].endTimeMinutes'],
          description: 'Minute-of-day when the repeating slot ends. It must be later than the start time. Weekly session occurrences are same-day ranges; to represent two separate days, select multiple days or add additional timeslots rather than making one session cross midnight.',
        },
        {
          path: 'leagueSlots[].startDate',
          label: 'Timeslot Start Date & Time',
          inputType: 'date-time picker',
          visibleWhen: 'Visible when Repeats weekly is off.',
          requiredWhen: 'Required for non-repeating slots.',
          defaultOrPreset: 'Existing slot startDate or blank.',
          createsOrUpdates: ['timeSlots[].startDate', 'timeSlots[].startTimeMinutes', 'timeSlots[].dayOfWeek'],
          description: 'Explicit one-time start datetime for a non-repeating slot. The form derives dayOfWeek and startTimeMinutes from this value for serialized compatibility.',
        },
        {
          path: 'leagueSlots[].endDate',
          label: 'Timeslot End Date & Time',
          inputType: 'date-time picker',
          visibleWhen: 'Visible when Repeats weekly is off.',
          requiredWhen: 'Required for non-repeating slots and must be after slot start.',
          defaultOrPreset: 'Existing slot endDate or blank.',
          createsOrUpdates: ['timeSlots[].endDate', 'timeSlots[].endTimeMinutes'],
          description: 'Explicit one-time end datetime for a non-repeating slot. Used mainly for tournament/league scheduling blocks or rental-created slots that should not recur.',
        },
        {
          path: 'playoffData',
          label: 'Playoffs Configuration',
          inputType: 'TournamentFields panel',
          visibleWhen: 'Visible for League events when playoffs are enabled and splitLeaguePlayoffDivisions is false.',
          requiredWhen: 'Required when visible; follows tournament config validation.',
          defaultOrPreset: 'Existing playoff config extracted from the event, otherwise tournament defaults.',
          createsOrUpdates: ['doubleElimination', 'winnerSetCount', 'loserSetCount', 'winnerBracketPointsToVictory', 'loserBracketPointsToVictory', 'restTimeMinutes'],
          description: 'Configures the single playoff bracket used after league standings when split playoff divisions are not used. Duration controls are hidden in this panel because league duration settings drive scheduling.',
        },
      ],
    },
  ],
};

export const shouldIncludeEventFormAgentContext = (pageContext: AgentPageContext | null): boolean => (
  pageContext?.page?.kind === 'event_schedule'
  && pageContext.page.activeTab === 'details'
);

export const getEventFormAgentContext = (
  pageContext: AgentPageContext | null,
): EventFormAgentContext | null => (
  shouldIncludeEventFormAgentContext(pageContext) ? eventFormAgentContext : null
);
