import { LeagueScoringConfig, Sport } from '@/types';

export const createSport = (overrides: Partial<Sport> = {}): Sport => ({
  $id: overrides.$id ?? '',
  name: overrides.name ?? '',
  officialPositionTemplates: overrides.officialPositionTemplates ?? [],
  usePointsForWin: overrides.usePointsForWin ?? false,
  usePointsForDraw: overrides.usePointsForDraw ?? false,
  usePointsForLoss: overrides.usePointsForLoss ?? false,
  usePointsForForfeitWin: overrides.usePointsForForfeitWin ?? false,
  usePointsForForfeitLoss: overrides.usePointsForForfeitLoss ?? false,
  usePointsPerSetWin: overrides.usePointsPerSetWin ?? false,
  usePointsPerSetLoss: overrides.usePointsPerSetLoss ?? false,
  usePointsPerGameWin: overrides.usePointsPerGameWin ?? false,
  usePointsPerGameLoss: overrides.usePointsPerGameLoss ?? false,
  usePointsPerGoalScored: overrides.usePointsPerGoalScored ?? false,
  usePointsPerGoalConceded: overrides.usePointsPerGoalConceded ?? false,
  useMaxGoalBonusPoints: overrides.useMaxGoalBonusPoints ?? false,
  useMinGoalBonusThreshold: overrides.useMinGoalBonusThreshold ?? false,
  usePointsForShutout: overrides.usePointsForShutout ?? false,
  usePointsForCleanSheet: overrides.usePointsForCleanSheet ?? false,
  useApplyShutoutOnlyIfWin: overrides.useApplyShutoutOnlyIfWin ?? false,
  usePointsPerGoalDifference: overrides.usePointsPerGoalDifference ?? false,
  useMaxGoalDifferencePoints: overrides.useMaxGoalDifferencePoints ?? false,
  usePointsPenaltyPerGoalDifference: overrides.usePointsPenaltyPerGoalDifference ?? false,
  usePointsForParticipation: overrides.usePointsForParticipation ?? false,
  usePointsForNoShow: overrides.usePointsForNoShow ?? false,
  usePointsForWinStreakBonus: overrides.usePointsForWinStreakBonus ?? false,
  useWinStreakThreshold: overrides.useWinStreakThreshold ?? false,
  usePointsForOvertimeWin: overrides.usePointsForOvertimeWin ?? false,
  usePointsForOvertimeLoss: overrides.usePointsForOvertimeLoss ?? false,
  useOvertimeEnabled: overrides.useOvertimeEnabled ?? false,
  usePointsPerRedCard: overrides.usePointsPerRedCard ?? false,
  usePointsPerYellowCard: overrides.usePointsPerYellowCard ?? false,
  usePointsPerPenalty: overrides.usePointsPerPenalty ?? false,
  useMaxPenaltyDeductions: overrides.useMaxPenaltyDeductions ?? false,
  useMaxPointsPerMatch: overrides.useMaxPointsPerMatch ?? false,
  useMinPointsPerMatch: overrides.useMinPointsPerMatch ?? false,
  useGoalDifferenceTiebreaker: overrides.useGoalDifferenceTiebreaker ?? false,
  useHeadToHeadTiebreaker: overrides.useHeadToHeadTiebreaker ?? false,
  useTotalGoalsTiebreaker: overrides.useTotalGoalsTiebreaker ?? false,
  useEnableBonusForComebackWin: overrides.useEnableBonusForComebackWin ?? false,
  useBonusPointsForComebackWin: overrides.useBonusPointsForComebackWin ?? false,
  useEnableBonusForHighScoringMatch: overrides.useEnableBonusForHighScoringMatch ?? false,
  useHighScoringThreshold: overrides.useHighScoringThreshold ?? false,
  useBonusPointsForHighScoringMatch: overrides.useBonusPointsForHighScoringMatch ?? false,
  useEnablePenaltyUnsporting: overrides.useEnablePenaltyUnsporting ?? false,
  usePenaltyPointsUnsporting: overrides.usePenaltyPointsUnsporting ?? false,
  usePointPrecision: overrides.usePointPrecision ?? false,
  $createdAt: overrides.$createdAt ?? '',
  $updatedAt: overrides.$updatedAt ?? '',
});

export const createLeagueScoringConfig = (
  overrides?: Partial<LeagueScoringConfig> | null,
): LeagueScoringConfig => {
  const safeOverrides: Partial<LeagueScoringConfig> =
    overrides && typeof overrides === 'object' ? overrides : {};

  return {
    pointsForWin: safeOverrides.pointsForWin ?? 0,
    pointsForDraw: safeOverrides.pointsForDraw ?? 0,
    pointsForLoss: safeOverrides.pointsForLoss ?? 0,
    pointsPerSetWin: safeOverrides.pointsPerSetWin ?? 0,
    pointsPerSetLoss: safeOverrides.pointsPerSetLoss ?? 0,
    pointsPerGameWin: safeOverrides.pointsPerGameWin ?? 0,
    pointsPerGameLoss: safeOverrides.pointsPerGameLoss ?? 0,
    pointsPerGoalScored: safeOverrides.pointsPerGoalScored ?? 0,
    pointsPerGoalConceded: safeOverrides.pointsPerGoalConceded ?? 0,
    $id: safeOverrides.$id ?? undefined,
    $createdAt: safeOverrides.$createdAt ?? '',
    $updatedAt: safeOverrides.$updatedAt ?? '',
  };
};
