import type { UseStaffOfficialControllerParams } from './staffOfficialControllerTypes';
import { useOfficialAssignmentsController } from './useOfficialAssignmentsController';
import { useStaffInviteController } from './useStaffInviteController';
import { useStaffRosterController } from './useStaffRosterController';

export const useStaffOfficialController = (params: UseStaffOfficialControllerParams) => {
    const roster = useStaffRosterController({
        activeEditingEvent: params.activeEditingEvent,
        currentUser: params.currentUser,
        eventData: params.eventData,
        incomingEvent: params.incomingEvent,
        isOrganizationHostedEvent: params.isOrganizationHostedEvent,
        resolvedOrganization: params.resolvedOrganization,
        setEventData: params.setEventData,
    });
    const invitations = useStaffInviteController({
        activeEditingEvent: params.activeEditingEvent,
        assignedUserIdsByRole: roster.assignedUserIdsByRole,
        getValues: params.getValues,
        isOrganizationHostedEvent: params.isOrganizationHostedEvent,
        setPendingStaffInvites: params.setPendingStaffInvites,
    });
    const officialAssignments = useOfficialAssignmentsController({
        eventData: params.eventData,
        fields: params.fields,
        isOrganizationHostedEvent: params.isOrganizationHostedEvent,
        organizationAllowedOfficialIdSet: roster.organizationAllowedOfficialIdSet,
        organizationOfficialsById: roster.organizationOfficialsById,
        selectedFieldIds: params.selectedFieldIds,
        selectedSportForOfficials: params.selectedSportForOfficials,
        setEventData: params.setEventData,
        setValue: params.setValue,
    });

    return {
        assignedActiveOfficialsForStaffing: officialAssignments.assignedActiveOfficialsForStaffing,
        assignedHostCards: roster.assignedHostCards,
        assignedOfficialCards: roster.assignedOfficialCards,
        assignedUserIdSetByRole: roster.assignedUserIdSetByRole,
        assistantHostValue: roster.assistantHostValue,
        availableOfficialFieldOptions: officialAssignments.availableOfficialFieldOptions,
        eventOfficialByUserId: officialAssignments.eventOfficialByUserId,
        filteredOrganizationStaffEntries: roster.filteredOrganizationStaffEntries,
        handleAddAssistantHost: roster.handleAddAssistantHost,
        handleAddOfficial: officialAssignments.handleAddOfficial,
        handleAddOfficialPosition: officialAssignments.handleAddOfficialPosition,
        handleAssignedHostsScroll: roster.handleAssignedHostsScroll,
        handleAssignedOfficialsScroll: roster.handleAssignedOfficialsScroll,
        handleHostChange: roster.handleHostChange,
        handleInviteFieldChange: invitations.handleInviteFieldChange,
        handleInviteRoleToggle: invitations.handleInviteRoleToggle,
        handleOrganizationStaffScroll: roster.handleOrganizationStaffScroll,
        handleRemoveAssistantHost: roster.handleRemoveAssistantHost,
        handleRemoveOfficial: officialAssignments.handleRemoveOfficial,
        handleRemoveOfficialPosition: officialAssignments.handleRemoveOfficialPosition,
        handleRemovePendingStaffInviteRole: invitations.handleRemovePendingStaffInviteRole,
        handleResetOfficialPositionsFromSport: officialAssignments.handleResetOfficialPositionsFromSport,
        handleStagePendingStaffInvite: invitations.handleStagePendingStaffInvite,
        handleUpdateEventOfficialEligibility: officialAssignments.handleUpdateEventOfficialEligibility,
        handleUpdateOfficialPosition: officialAssignments.handleUpdateOfficialPosition,
        hostCardVisibleCount: roster.hostCardVisibleCount,
        newStaffInvite: invitations.newStaffInvite,
        nonOrgStaffError: roster.nonOrgStaffError,
        nonOrgStaffResults: roster.nonOrgStaffResults,
        nonOrgStaffSearch: roster.nonOrgStaffSearch,
        nonOrgStaffSearchLoading: roster.nonOrgStaffSearchLoading,
        officialCardVisibleCount: roster.officialCardVisibleCount,
        officialStaffingCoverageError: officialAssignments.officialStaffingCoverageError,
        organizationAllowedHostIds: roster.organizationAllowedHostIds,
        organizationAllowedOfficialIds: roster.organizationAllowedOfficialIds,
        organizationOfficialsById: roster.organizationOfficialsById,
        organizationStaffSearch: roster.organizationStaffSearch,
        organizationStaffStatusFilter: roster.organizationStaffStatusFilter,
        organizationStaffTypeFilter: roster.organizationStaffTypeFilter,
        organizationStaffVisibleCount: roster.organizationStaffVisibleCount,
        requiredOfficialSlotsPerMatch: officialAssignments.requiredOfficialSlotsPerMatch,
        setNonOrgStaffSearch: roster.setNonOrgStaffSearch,
        setOrganizationStaffSearch: roster.setOrganizationStaffSearch,
        setOrganizationStaffStatusFilter: roster.setOrganizationStaffStatusFilter,
        setOrganizationStaffTypeFilter: roster.setOrganizationStaffTypeFilter,
        sportOfficialPositionTemplates: officialAssignments.sportOfficialPositionTemplates,
        staffInviteError: invitations.staffInviteError,
        validatePendingStaffAssignments: invitations.validatePendingStaffAssignments,
    };
};
