import type { AffiliateScrapeMapping, ScrapePageClient } from './types';

export const CASCADE_GRESHAM_HOME_URL = 'https://cascadeac.com/';
export const CASCADE_GRESHAM_LIST_URL = 'https://cascadeac.com/gresham/sports-programs/';
export const CASCADE_GRESHAM_BASKETBALL_URL = `${CASCADE_GRESHAM_LIST_URL}basketball/`;
export const CASCADE_GRESHAM_PICKLEBALL_URL = `${CASCADE_GRESHAM_LIST_URL}pickleball/`;
export const CASCADE_GRESHAM_RACQUETBALL_URL = `${CASCADE_GRESHAM_LIST_URL}racquetball/`;
export const CASCADE_GRESHAM_TENNIS_URL = `${CASCADE_GRESHAM_LIST_URL}tennis/`;
export const CASCADE_GRESHAM_CLUB_AUTOMATION_URL = 'https://cascadeac.clubautomation.com/';
export const CASCADE_GRESHAM_TENNIS_DOUBLES_FORM_URL =
  'https://docs.google.com/forms/d/1Fhl7Jzd1YURHpZpVt3nhEmEEFpGqrvZSyjLihd6tqrE/viewform?edit_requested=true';
export const CASCADE_GRESHAM_LOGO_SOURCE_URL =
  'https://cascadeac.com/wp-content/uploads/2024/04/logo-blue.png';
export const CASCADE_GRESHAM_ADDRESS = '19201 SE Division St, Gresham, OR 97030';
export const CASCADE_GRESHAM_ORG_DESCRIPTION =
  'Cascade Athletic Clubs Gresham is a multi-sport athletic club with basketball, pickleball, racquetball, tennis, swimming, fitness, youth programs, court reservations, and club sports programming.';

const ORGANIZER_NAME = 'Cascade Athletic Clubs Gresham';

export const CASCADE_GRESHAM_SOURCE_EVIDENCE = {
  schemaVersion: 1,
  evidenceSystem: 'AffiliateSourceIntakes',
  environment: 'live',
  intakeId: 'ee3e611e-281b-4af8-a3bf-eea8cb7a3c39',
  intakeSourceKey: 'site-cascadeac-com',
  intakeName: ORGANIZER_NAME,
  baseUrl: 'https://cascadeac.com',
  complianceStatus: 'ALLOWED',
  runId: 'ee59cc84-2887-4530-9ba3-d93f57a7104c',
  runStatus: 'SUCCEEDED',
  provider: 'FIRECRAWL',
  capturedAt: '2026-07-19T23:50:08.005Z',
  pages: [
    { url: CASCADE_GRESHAM_HOME_URL, role: 'HOME', robotsStatus: 'ALLOWED' },
    { url: CASCADE_GRESHAM_LIST_URL, role: 'LISTING', robotsStatus: 'ALLOWED' },
    { url: CASCADE_GRESHAM_TENNIS_URL.replace(/\/$/, ''), role: 'LISTING', robotsStatus: 'UNCHECKED' },
    { url: CASCADE_GRESHAM_RACQUETBALL_URL.replace(/\/$/, ''), role: 'LISTING', robotsStatus: 'UNCHECKED' },
    { url: CASCADE_GRESHAM_PICKLEBALL_URL.replace(/\/$/, ''), role: 'LISTING', robotsStatus: 'UNCHECKED' },
    { url: CASCADE_GRESHAM_BASKETBALL_URL.replace(/\/$/, ''), role: 'LISTING', robotsStatus: 'UNCHECKED' },
  ],
  artifactKinds: [
    { kind: 'DISCOVERED_URLS', count: 1 },
    { kind: 'LOGO_CANDIDATE', count: 10 },
    { kind: 'PAGE_BRANDING', count: 2 },
    { kind: 'PAGE_HTML', count: 2 },
    { kind: 'PAGE_IMAGES', count: 2 },
    { kind: 'PAGE_LINKS', count: 2 },
    { kind: 'PAGE_MARKDOWN', count: 2 },
    { kind: 'PAGE_SCREENSHOT', count: 2 },
    { kind: 'PROVIDER_MAP_REQUEST_JSON', count: 1 },
    { kind: 'PROVIDER_MAP_RESPONSE_JSON', count: 1 },
    { kind: 'PROVIDER_SCRAPE_REQUEST_JSON', count: 2 },
    { kind: 'PROVIDER_SCRAPE_RESPONSE_JSON', count: 2 },
    { kind: 'ROBOTS', count: 2 },
  ],
} as const;

export const CASCADE_GRESHAM_WITHHELD_ROWS = [
  {
    title: 'Pickleball clinics and classes',
    sourceUrl: CASCADE_GRESHAM_PICKLEBALL_URL,
    reason: 'The reviewed page lists month/day sessions without a year, so no current event date is inferred.',
  },
  {
    title: 'Pickleball tournaments',
    sourceUrl: CASCADE_GRESHAM_PICKLEBALL_URL,
    reason: 'The source says tournaments are coming soon and does not publish a dated tournament or registration target.',
  },
  {
    title: 'Racquetball junior and high-school classes',
    sourceUrl: CASCADE_GRESHAM_RACQUETBALL_URL,
    reason: 'The source publishes recurring weekdays and prices but no current term or date window.',
  },
  {
    title: 'Tennis adult mixers and open-play rows',
    sourceUrl: CASCADE_GRESHAM_TENNIS_URL,
    reason: 'Adult mixers are marked coming in 2026 and the remaining membership programs do not publish stable current registration windows.',
  },
] as const;

export const CASCADE_GRESHAM_MANUAL_CANDIDATES = [
  {
    listingKind: 'EVENT' as const,
    title: "Cascade Gresham Men's 4-on-4 Basketball League",
    officialActionUrl: CASCADE_GRESHAM_BASKETBALL_URL,
    sourceUrl: CASCADE_GRESHAM_BASKETBALL_URL,
    organizerName: ORGANIZER_NAME,
    sportName: 'Basketball',
    formatLabel: 'Basketball league',
    city: 'Gresham, OR',
    venueName: ORGANIZER_NAME,
    address: CASCADE_GRESHAM_ADDRESS,
    timeZone: 'America/Los_Angeles',
    scheduleText: 'Thursday league games are listed from 6:00-10:00 PM. Current fall league dates are marked coming soon on the source page.',
    dateDisplayMode: 'NO_FIXED_DATE' as const,
    dateDisplayText: 'Fall league details coming soon',
    skillLevel: 'Adult recreational basketball',
    ageGroup: '18+; 16-17 with director approval',
    participantOptionsText: 'Players may sign up as individuals or as a team. Non-members must be sponsored by a member.',
    priceText: '$20-$90',
    statusText: 'Fall leagues are marked coming soon on the source page.',
    description: "Cascade Athletic Clubs Gresham lists a men's 4-on-4 basketball league with weekly Thursday games, round-robin play, playoffs, and a pizza party after each season. The source says players can join as individuals or teams, rosters are due before the season starts, adults 18+ are eligible, and 16-17 year olds may play with director approval. Public pricing is listed as $20 per season for members and $90 per season for non-members.",
    tags: ['League'],
    tagText: 'League',
    divisions: [{
      name: "Men's 18+",
      key: 'm_rec_18plus',
      gender: 'M' as const,
      ratingType: 'AGE' as const,
      skillDivisionTypeId: 'rec',
      ageDivisionTypeId: 'adult',
      ageCutoffLabel: '18+',
      ageCutoffSource: CASCADE_GRESHAM_BASKETBALL_URL,
    }],
    warnings: ['Stored as a no-fixed-date program because current fall league dates were marked coming soon during inspection.'],
  },
  {
    listingKind: 'EVENT' as const,
    title: 'Cascade Gresham 40+ Basketball Open Play',
    officialActionUrl: CASCADE_GRESHAM_BASKETBALL_URL,
    sourceUrl: CASCADE_GRESHAM_BASKETBALL_URL,
    organizerName: ORGANIZER_NAME,
    sportName: 'Basketball',
    formatLabel: 'Open play',
    city: 'Gresham, OR',
    venueName: ORGANIZER_NAME,
    address: CASCADE_GRESHAM_ADDRESS,
    timeZone: 'America/Los_Angeles',
    scheduleText: 'Tuesdays 5:00-7:30 PM in Gym 1.',
    dateDisplayMode: 'ONGOING' as const,
    dateDisplayText: 'Tuesdays 5:00-7:30 PM',
    skillLevel: 'Adult open play',
    ageGroup: '40+',
    participantOptionsText: 'No signup required according to the source page.',
    priceText: 'Free',
    statusText: 'Free for members.',
    description: 'Cascade Athletic Clubs Gresham lists 40+ basketball open play on Tuesdays from 5:00-7:30 PM in Gym 1. The source describes it as 4-on-4 basketball with no signup required and free access for members.',
    tags: ['Open Play'],
    tagText: 'Open Play',
    divisions: [{
      name: 'Coed 40+',
      key: 'c_open_40plus',
      gender: 'C' as const,
      ratingType: 'AGE' as const,
      skillDivisionTypeId: 'open',
      ageDivisionTypeId: 'adult',
      priceCents: 0,
      ageCutoffLabel: '40+',
      ageCutoffSource: CASCADE_GRESHAM_BASKETBALL_URL,
    }],
  },
  {
    listingKind: 'EVENT' as const,
    title: 'Cascade Gresham Pickleball Leagues',
    officialActionUrl: CASCADE_GRESHAM_CLUB_AUTOMATION_URL,
    sourceUrl: CASCADE_GRESHAM_PICKLEBALL_URL,
    organizerName: ORGANIZER_NAME,
    sportName: 'Pickleball',
    formatLabel: 'Pickleball league',
    city: 'Gresham, OR',
    venueName: ORGANIZER_NAME,
    address: CASCADE_GRESHAM_ADDRESS,
    timeZone: 'America/Los_Angeles',
    scheduleText: 'Monday leagues are listed 6:00-8:30 PM and Wednesday leagues are listed 5:00-9:00 PM.',
    dateDisplayMode: 'ONGOING' as const,
    dateDisplayText: 'Monday and Wednesday pickleball leagues',
    skillLevel: 'Recreational pickleball league play',
    ageGroup: 'Adult',
    participantOptionsText: 'Individual registration through the official Cascade booking flow. The source lists a 48-player limit.',
    maxParticipantsText: '48 players',
    priceText: '$20-$30',
    statusText: 'Current league availability is handled in Cascade Club Automation.',
    description: 'Cascade Athletic Clubs Gresham lists pickleball leagues on Mondays from 6:00-8:30 PM and Wednesdays from 5:00-9:00 PM. The public source page lists a 48-player limit and membership-dependent per-person pricing: Tennis and Pickleball members $20, members $25, and non-members $30. Current registration and availability are handled through the official Cascade Club Automation flow.',
    tags: ['League'],
    tagText: 'League',
    divisions: [{
      name: 'Coed recreational',
      key: 'c_rec_adult',
      gender: 'C' as const,
      ratingType: 'SKILL' as const,
      skillDivisionTypeId: 'rec',
      ageDivisionTypeId: 'adult',
      maxParticipants: 48,
    }],
    warnings: ['ClubAutomation robots.txt disallows scraping, so it is used only as the official action URL.'],
  },
  {
    listingKind: 'EVENT' as const,
    title: 'Cascade Gresham Racquetball Singles Open Play',
    officialActionUrl: CASCADE_GRESHAM_CLUB_AUTOMATION_URL,
    sourceUrl: CASCADE_GRESHAM_RACQUETBALL_URL,
    organizerName: ORGANIZER_NAME,
    sportName: 'Racquetball',
    formatLabel: 'Open play',
    city: 'Gresham, OR',
    venueName: ORGANIZER_NAME,
    address: CASCADE_GRESHAM_ADDRESS,
    timeZone: 'America/Los_Angeles',
    scheduleText: 'Mondays at 6:30 PM.',
    dateDisplayMode: 'ONGOING' as const,
    dateDisplayText: 'Mondays at 6:30 PM',
    skillLevel: 'Beginner-friendly singles open play',
    ageGroup: 'Adult',
    participantOptionsText: 'The source welcomes beginners and links to official online registration.',
    maxParticipantsText: '20 players',
    priceText: 'Free-$20',
    statusText: 'Free for members; non-members pay $20.',
    description: 'Cascade Athletic Clubs Gresham lists beginner-friendly singles racquetball open play every Monday at 6:30 PM. The public page lists a 20-player capacity, free participation for members, and a $20 price for non-members, with registration handled through the official Cascade flow.',
    tags: ['Open Play'],
    tagText: 'Open Play',
    divisions: [{
      name: 'Coed open',
      key: 'c_open_adult',
      gender: 'C' as const,
      ratingType: 'SKILL' as const,
      skillDivisionTypeId: 'open',
      ageDivisionTypeId: 'adult',
      maxParticipants: 20,
    }],
    warnings: ['ClubAutomation robots.txt disallows scraping, so it is used only as the official action URL.'],
  },
  {
    listingKind: 'EVENT' as const,
    title: "Cascade Gresham Men's 4.0 Tennis Doubles Flights",
    officialActionUrl: CASCADE_GRESHAM_TENNIS_DOUBLES_FORM_URL,
    sourceUrl: CASCADE_GRESHAM_TENNIS_URL,
    organizerName: ORGANIZER_NAME,
    sportName: 'Tennis',
    formatLabel: 'Tennis doubles program',
    city: 'Gresham, OR',
    venueName: ORGANIZER_NAME,
    address: CASCADE_GRESHAM_ADDRESS,
    timeZone: 'America/Los_Angeles',
    scheduleText: 'Tuesdays 6:45-8:45 PM; monthly doubles flights with rotating partners.',
    dateDisplayMode: 'NO_FIXED_DATE' as const,
    dateDisplayText: 'Tuesdays 6:45-8:45 PM; monthly signup',
    skillLevel: "Men's 4.0",
    ageGroup: 'Adult',
    divisionText: "Men's 4.0",
    participantOptionsText: 'Players rotate partners after each set and sign up monthly through the Tennis Office or official Google Form.',
    statusText: 'No stable public price was visible on the source page.',
    description: "Cascade Athletic Clubs Gresham lists a men's 4.0 doubles flight on Tuesdays from 6:45-8:45 PM. Players rotate partners after each set, and the top game winners move up to a higher court each week. The public page directs players to sign up monthly through the Tennis Office and exposes an official Google Form, but no stable public price is stated.",
    tags: ['Doubles'],
    tagText: 'Doubles',
    divisions: [{
      name: "Men's 4.0",
      key: 'm_4_0_adult',
      gender: 'M' as const,
      ratingType: 'SKILL' as const,
      divisionTypeId: '4_0',
      skillDivisionTypeId: '4_0',
      ageDivisionTypeId: 'adult',
    }],
    warnings: ['Stored as no-fixed-date because the source describes the monthly program but does not publish a stable current session date range.'],
  },
  {
    listingKind: 'RENTAL' as const,
    title: 'Cascade Gresham Pickleball Court Reservations',
    officialActionUrl: CASCADE_GRESHAM_CLUB_AUTOMATION_URL,
    sourceUrl: CASCADE_GRESHAM_PICKLEBALL_URL,
    organizerName: ORGANIZER_NAME,
    sportName: 'Pickleball',
    formatLabel: 'Pickleball court rental',
    city: 'Gresham, OR',
    venueName: ORGANIZER_NAME,
    address: CASCADE_GRESHAM_ADDRESS,
    timeZone: 'America/Los_Angeles',
    scheduleText: 'Court reservations are handled through the official Cascade app or Club Automation link.',
    dateDisplayMode: 'ONGOING' as const,
    dateDisplayText: 'Reserve current court availability online',
    participantOptionsText: 'The Gresham page lists six indoor courts and four outdoor courts. Tennis or Pickleball members can reserve up to 7 days ahead; other members may make same-day reservations at no cost.',
    statusText: 'Current reservation availability is handled in Cascade Club Automation.',
    description: 'Cascade Athletic Clubs Gresham lists pickleball court reservations for its six indoor courts and four outdoor courts. The public page says all court usage requires a reservation, two names are required for each one-hour reservation, Tennis or Pickleball members can reserve up to 7 days ahead, and members without a Tennis or Pickleball membership may make same-day court reservations at no cost. Current availability is handled through the official Cascade app or Club Automation flow.',
    warnings: ['Stored as a rental link-out because real-time court availability is in Club Automation, which disallows scraping.'],
  },
] satisfies NonNullable<AffiliateScrapeMapping['manualCandidates']>;

export const CASCADE_GRESHAM_MAPPING: AffiliateScrapeMapping = {
  kind: 'EVENT',
  listUrl: CASCADE_GRESHAM_LIST_URL,
  itemSelector: 'body',
  fields: {
    title: { selector: 'body', mode: 'literal', value: 'Cascade Athletic Clubs Gresham Sports Programs' },
    officialActionUrl: { selector: 'body', mode: 'literal', value: CASCADE_GRESHAM_LIST_URL },
  },
  dedupe: { fields: ['officialActionUrl', 'title', 'dateDisplayMode'] },
  manualCandidates: CASCADE_GRESHAM_MANUAL_CANDIDATES,
};

export const CASCADE_GRESHAM_STATIC_PAGE_CLIENT: ScrapePageClient = {
  async fetchPage(params) {
    return {
      url: params.url,
      finalUrl: params.url,
      statusCode: 200,
      fetchedAt: new Date().toISOString(),
      body: '<!doctype html><html><body><main>Cascade Athletic Clubs Gresham reviewed public source.</main></body></html>',
    };
  },
};
