import { readFile } from 'node:fs/promises';
import path from 'node:path';
import type { AffiliateScrapeMapping, ScrapePageClient } from './types';

export const MANHATTAN_SOCCER_CLUB_HOME_URL = 'https://www.manhattansc.org/';
export const MANHATTAN_SOCCER_CLUB_TRYOUTS_URL = 'https://www.manhattansc.org/tryouts26';
export const MANHATTAN_SOCCER_CLUB_CAMPS_URL = 'https://www.manhattansc.org/camps-clinics/camps-2/';
export const MANHATTAN_SOCCER_CLUB_LOGO_SOURCE_URL = 'https://www.manhattansc.org/wp-content/uploads/2020/03/Manhattan-SC.png';
export const MANHATTAN_SOCCER_CLUB_ORG_DESCRIPTION = 'Manhattan Soccer Club is a New York City soccer club offering development and competition from ages 3 to 23, with camps, clinics, training, and youth programs.';
export const MANHATTAN_SOCCER_CLUB_SOURCE_EVIDENCE = {
  schemaVersion: 1, evidenceSystem: 'AffiliateSourceIntakes', environment: 'live', intakeId: '004fddf6-181d-4204-8193-1533f3f377a3', intakeSourceKey: 'new-york-new-york-metropolitan-area-manhattan-soccer-club-nyc-s-largest-soccer-club-manhattansc-org', intakeName: 'Manhattan Soccer Club', baseUrl: 'https://www.manhattansc.org', complianceStatus: 'ALLOWED', runId: 'e8726ad7-7415-41fa-8e54-4b02e160cc14', runStatus: 'PARTIAL', provider: 'SCRAPINGDOG', capturedAt: '2026-07-29T19:16:31.867Z', pages: [{ url: MANHATTAN_SOCCER_CLUB_HOME_URL, role: 'HOME', robotsStatus: 'ALLOWED' }, { url: MANHATTAN_SOCCER_CLUB_CAMPS_URL, role: 'LISTING', robotsStatus: 'UNCHECKED' }, { url: MANHATTAN_SOCCER_CLUB_TRYOUTS_URL, role: 'REGISTRATION', robotsStatus: 'UNCHECKED' }], artifacts: { logoCandidate: 'b17ff1e3b58f91f484ab0cc3db017a1c25db4c065e9fe74f438a896dbee08049', pageBranding: '8f92e28220323da5e536733f5a178586bc4ebe26d328384d2b7eb6307c9ec0b5', pageHtml: '2f77b77c334311c260a3ba7e41e41ef9f24b983d7270c774f7dab5db019c3b30', pageLinks: 'f66386bc2d69c99da21e94f3ccda86dcdbb167fdf78c0878a6f7c481490f512b', pageMarkdown: '848aa6a7d75b3d07ff9edf35d5989d6bd5f5af79e36dd0c833dfe811468e12e2', robots: 'b2385f54624d3efead9d859c0223b74e0b0fc18af0df87de4620724620adecac' },
} as const;
export const MANHATTAN_SOCCER_CLUB_MANUAL_CANDIDATES = [{ listingKind: 'CLUB' as const, title: 'Manhattan Soccer Club', officialActionUrl: MANHATTAN_SOCCER_CLUB_HOME_URL, sourceUrl: MANHATTAN_SOCCER_CLUB_HOME_URL, organizerName: 'Manhattan Soccer Club', sportName: 'Soccer', formatLabel: 'New York City youth soccer club', city: 'New York City, NY', venueName: null, address: null, dateDisplayMode: 'ONGOING' as const, dateDisplayText: 'Club programs, camps, clinics, and training', scheduleText: 'The stored homepage describes year-round supplemental clinics, camps, training, and youth development. Current event detail dates are withheld unless source-provided evidence includes a complete row.', statusText: 'Review-only club profile; current camps and tryouts require detail review.', description: MANHATTAN_SOCCER_CLUB_ORG_DESCRIPTION, tags: ['Club', 'Soccer', 'Youth'], warnings: ['The homepage links to Summer Camp 2026 and tryouts but the captured evidence does not provide a complete current event row with date, time, venue, price, and action.', 'No physical address is assigned because the stored homepage does not establish one canonical club address.', 'No TEAM candidate is created because team mappings are out of scope.'] }] satisfies NonNullable<AffiliateScrapeMapping['manualCandidates']>;
export const MANHATTAN_SOCCER_CLUB_MAPPING: AffiliateScrapeMapping = { kind: 'CLUB', listUrl: MANHATTAN_SOCCER_CLUB_HOME_URL, itemSelector: 'body', fields: { title: { selector: 'body', mode: 'literal', value: 'Manhattan Soccer Club' }, officialActionUrl: { selector: 'body', mode: 'literal', value: MANHATTAN_SOCCER_CLUB_HOME_URL }, sourceUrl: { selector: 'body', mode: 'literal', value: MANHATTAN_SOCCER_CLUB_HOME_URL }, organizerName: { selector: 'body', mode: 'literal', value: 'Manhattan Soccer Club' }, sportName: { selector: 'body', mode: 'literal', value: 'Soccer' }, formatLabel: { selector: 'body', mode: 'literal', value: 'New York City youth soccer club' }, city: { selector: 'body', mode: 'literal', value: 'New York City, NY' }, dateDisplayMode: { selector: 'body', mode: 'literal', value: 'ONGOING' }, dateDisplayText: { selector: 'body', mode: 'literal', value: 'Club programs, camps, clinics, and training' }, scheduleText: { selector: 'body', mode: 'literal', value: 'The stored homepage describes year-round supplemental clinics, camps, training, and youth development; dated rows are withheld.' }, description: { selector: 'body', mode: 'literal', value: MANHATTAN_SOCCER_CLUB_ORG_DESCRIPTION }, tagText: { selector: 'body', mode: 'literal', value: 'Club, Soccer, Youth' } }, dedupe: { fields: ['officialActionUrl', 'title'] }, manualCandidates: MANHATTAN_SOCCER_CLUB_MANUAL_CANDIDATES };
const FIXTURE_PATH = path.join(process.cwd(), 'src/server/affiliateImports/fixtures/manhattanSoccerClub.html');
export const MANHATTAN_SOCCER_CLUB_STATIC_PAGE_CLIENT: ScrapePageClient = { async fetchPage(params) { return { url: params.url, finalUrl: params.url, statusCode: 200, fetchedAt: '2026-07-29T19:16:31.867Z', body: await readFile(FIXTURE_PATH, 'utf8') }; } };
