import { readFile } from 'node:fs/promises';
import path from 'node:path';
import type { AffiliateScrapeMapping, ScrapePageClient } from './types';

export const SPORTS_ZONE_SOFTBALL_HOME_URL = 'https://sportszoneacademy.com/softball/';
export const SPORTS_ZONE_SOFTBALL_TRAVEL_URL = 'https://sportszoneacademy.com/softball/softball-travel-teams';
export const SPORTS_ZONE_SOFTBALL_LOGO_SOURCE_URL = 'https://b4018554.smushcdn.com/4018554/wp-content/uploads/2025/04/cropped-Socialcardsportszone2-32x32.png?lossy=2&strip=1&webp=1';
export const SPORTS_ZONE_SOFTBALL_ORG_DESCRIPTION = 'Sports Zone Academy has operated a high-performance softball development program in Central New York since 2016 for athletes pursuing structured development and college opportunities.';

export const SPORTS_ZONE_SOFTBALL_SOURCE_EVIDENCE = {
  schemaVersion: 1, evidenceSystem: 'AffiliateSourceIntakes', environment: 'live', intakeId: '16a9b35f-7808-4e1b-bee3-50aad16b739b', intakeSourceKey: 'new-york-new-york-metropolitan-area-softball-sportszoneacademy-com', intakeName: 'New York Softball', baseUrl: 'https://sportszoneacademy.com', complianceStatus: 'ALLOWED', runId: '77eee6d1-cb0a-4553-af61-b1b25820f35f', runStatus: 'SUCCEEDED', provider: 'SCRAPINGDOG', capturedAt: '2026-07-29T19:24:01.040Z', pages: [{ url: SPORTS_ZONE_SOFTBALL_HOME_URL, role: 'LISTING', robotsStatus: 'ALLOWED' }, { url: SPORTS_ZONE_SOFTBALL_TRAVEL_URL, role: 'DETAIL', robotsStatus: 'ALLOWED' }, { url: 'https://sportszoneacademy.com/softball/softball-training', role: 'DETAIL', robotsStatus: 'UNCHECKED' }, { url: 'https://sportszoneacademy.com/sports-zone-softball-tryouts-2026', role: 'REGISTRATION', robotsStatus: 'UNCHECKED' }], artifactKinds: [{ kind: 'DISCOVERED_URLS', count: 1 }, { kind: 'LOGO_CANDIDATE', count: 2 }, { kind: 'PAGE_BRANDING', count: 2 }, { kind: 'PAGE_HTML', count: 2 }, { kind: 'PAGE_IMAGES', count: 2 }, { kind: 'PAGE_LINKS', count: 2 }, { kind: 'PAGE_MARKDOWN', count: 2 }, { kind: 'PAGE_SCREENSHOT', count: 1 }, { kind: 'PROVIDER_MAP_REQUEST_JSON', count: 1 }, { kind: 'PROVIDER_MAP_RESPONSE_JSON', count: 1 }, { kind: 'PROVIDER_SCRAPE_REQUEST_JSON', count: 2 }, { kind: 'PROVIDER_SCRAPE_RESPONSE_JSON', count: 2 }, { kind: 'ROBOTS', count: 2 }],
} as const;

export const SPORTS_ZONE_SOFTBALL_MANUAL_CANDIDATES = [{ listingKind: 'CLUB' as const, title: 'Sports Zone Academy Softball', officialActionUrl: SPORTS_ZONE_SOFTBALL_HOME_URL, sourceUrl: SPORTS_ZONE_SOFTBALL_HOME_URL, organizerName: 'Sports Zone Academy', sportName: 'Softball', formatLabel: 'High-performance softball development, training, travel teams, and college-bound player development', city: 'Central New York', venueName: null, address: null, dateDisplayMode: 'ONGOING' as const, dateDisplayText: 'Softball development program', scheduleText: 'The stored softball pages describe a structured high-performance development program and travel-team age groups from 10u through 18u. Current program dates, locations, prices, and registration rows are withheld.', statusText: 'Review-only club profile; current training, tryout, and play-day details require complete captured rows.', description: SPORTS_ZONE_SOFTBALL_ORG_DESCRIPTION, tags: ['Club', 'Softball', 'Youth', 'Development'], logoUrl: SPORTS_ZONE_SOFTBALL_LOGO_SOURCE_URL, logoSourceUrl: SPORTS_ZONE_SOFTBALL_LOGO_SOURCE_URL, warnings: ['The stored capture contains travel-team roster headings but no complete current event rows; no TEAM candidate is created.', 'The only supportable stored brand asset is the first-party favicon/logo candidate, normalized without changing the mark.', 'No street address is assigned because the stored pages identify Central New York but do not publish a canonical facility address.'] }] satisfies NonNullable<AffiliateScrapeMapping['manualCandidates']>;

export const SPORTS_ZONE_SOFTBALL_MAPPING: AffiliateScrapeMapping = { kind: 'CLUB', listUrl: SPORTS_ZONE_SOFTBALL_HOME_URL, itemSelector: 'body', fields: { title: { selector: 'body', mode: 'literal', value: 'Sports Zone Academy Softball' }, officialActionUrl: { selector: 'body', mode: 'literal', value: SPORTS_ZONE_SOFTBALL_HOME_URL }, sourceUrl: { selector: 'body', mode: 'literal', value: SPORTS_ZONE_SOFTBALL_HOME_URL }, organizerName: { selector: 'body', mode: 'literal', value: 'Sports Zone Academy' }, sportName: { selector: 'body', mode: 'literal', value: 'Softball' }, formatLabel: { selector: 'body', mode: 'literal', value: 'High-performance softball development, training, travel teams, and college-bound player development' }, city: { selector: 'body', mode: 'literal', value: 'Central New York' }, dateDisplayMode: { selector: 'body', mode: 'literal', value: 'ONGOING' }, dateDisplayText: { selector: 'body', mode: 'literal', value: 'Softball development program' }, description: { selector: 'body', mode: 'literal', value: SPORTS_ZONE_SOFTBALL_ORG_DESCRIPTION }, tagText: { selector: 'body', mode: 'literal', value: 'Club, Softball, Youth, Development' } }, dedupe: { fields: ['officialActionUrl', 'title'] }, manualCandidates: SPORTS_ZONE_SOFTBALL_MANUAL_CANDIDATES };
const FIXTURE_PATH = path.join(process.cwd(), 'src/server/affiliateImports/fixtures/sportsZoneAcademySoftball.html');
export const SPORTS_ZONE_SOFTBALL_STATIC_PAGE_CLIENT: ScrapePageClient = { async fetchPage(params) { return { url: params.url, finalUrl: params.url, statusCode: 200, fetchedAt: SPORTS_ZONE_SOFTBALL_SOURCE_EVIDENCE.capturedAt, body: await readFile(FIXTURE_PATH, 'utf8') }; } };
